// Generated by  on 2015-01-27 오후 5:15:30
define(
  [
      'app/views/page/PWF/020/PWF020-base',
      'app/views/page/PWF/020/PWF020-list',
      'app/views/page/PWF/020/PWF020-detl',
      'text!app/views/page/PWF/020/_PWF020-tpl.html'
  ],
  function (
      PWF020Base,
      PWF020List,
      PWF020Detl,
      tpl
  ) {


      var PWF020View = Backbone.View.extend({


          // 태그이름 설정
          tagName: 'section'


          // 클래스이름 설정
          ,className: 'bx-container bxp-PWF020001-page'


          // 템플릿 설정
          ,templates: {
              'tpl': tpl
          }


          ,initialize: function (initData) {
              var that = this;


              $.extend(that, initData);
              // 페이지 템플릿 설정
              that.$el.html(that.tpl());


              // 페이지 핸들바 설정 : 메뉴의 메인 페이지에 설정해야 함 (_PWF020.js파일)
              that.$el.attr('data-page', that.pageHandler);


              // 기본정보영역 객체 생성
              that.subViews['PWF020Base'] = new PWF020Base();


              // 탭(그리드)영역 객체 생성
              that.subViews['PWF020List'] = new PWF020List();


              // 그리드 행별영역 객체 생성
              that.subViews['PWF020Detl'] = new PWF020Detl();


              // 초기화
              that.listenTo(that.subViews['PWF020Base'], 'reset', function() {
                  that.subViews['PWF020List'].reset();
                  that.subViews['PWF020Detl'].reset();
              });


              // tab의 현재 활성화된 그리드 조회
              that.listenTo(that.subViews['PWF020Base'], 'loadData', function(param) {
                  that.subViews['PWF020List'].renderSubPage(param);
              });


              that.listenTo(that.subViews['PWF020List'], 'loadProcessInstanceData', function(param){
            	  that.subViews['PWF020Detl'].renderProcessInstanceDetail(param);
              });
          } // end of initialize


          ,render: function() {
              // 기본정보영역 render
              this.$el.find('.PWF020-base-wrap').html(this.subViews['PWF020Base'].render());


              // 탭(그리드)정보영역 render
              this.$el.find('.PWF020-list-wrap').html(this.subViews['PWF020List'].render());


              // 그리드 행별정보영역 render
              this.$el.find('.PWF020-detl-wrap').html(this.subViews['PWF020Detl'].render());


              return this.$el;
          } // end of render
      });// Backbone.View.extend


      return PWF020View;


  } // end of function
);
