// Generated by Bankware Global CBB Solution Center on 2015-02-04-00:48:27


define(
    [
        'bx/common/config'
        , 'bx-component/message/message-alert'
        , 'bx-component/message/message-confirm'
        , 'bx-component/ext-grid/_ext-grid'
        , 'text!app/views/page/PWF/507/PWF507-list-tpl.html'
        , 'bx/common/common-message'
    ],
    function (config
        , alertMessage
        , confirmMessage
        , ExtGrid
        , tpl) {


        // 전역변수 선언
        var chkAddCol = false;


        var comboStore1 = {}; // 결재사유코드
        var comboStore2 = {}; // 결재패턴구분코드
        var comboStore3 = {}; // 결재조건상태코드


        var PWF507TabView = Backbone.View.extend({


            // 태그이름 설정
            tagName: 'section',


            // 클래스 이름 설정
            className: 'PWF507-list-page',


            // 템플릿 설정
            templates: {
                'tpl': tpl
            }


            // 이벤트 설정
            , events: {
                'click.bx-tab-container .bx-tab-menu-item': 'changeTab'
                , 'click .PWF-add-btn': 'addPWFList'
            }


            // 탭에 따라 호출될 메소드 지정
            , subPageRenderMap: {
                'PWF507-single-tab': 'selSingle'
            }


            , initialize: function (initData) {
                var that = this;


                $.extend(that, initData);


                // 페이지 템플릿 설정
                that.$el.html(that.tpl());


                // 콤보조회 서비스호출 준비
                var sParam = {};


                // 결재사유코드
                sParam = {};
                sParam.cdNbr = "12303";
                var linkData1 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                // 결재패턴구분코드
                sParam = {};
                sParam.cdNbr = "12302";
                var linkData2 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                // 결재조건상태코드
                sParam = {};
                sParam.cdNbr = "12307";
                var linkData3 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                /* ========================================================== */
                bxProxy.all([
                    /* ========================================================== */
                    // 결재사유코드콤보로딩
                    {
                        url: sUrl, param: JSON.stringify(linkData1), success: function (responseData) {
                        if (!responseData.header.errorMessageProcessed) {
                            comboStore1 = new Ext.data.Store({
                                fields: ['cd', 'cdNm'],
                                data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tbl
                            });
                        }
                    }
                    }
                    // 결재패턴구분코드콤보로딩
                    , {
                        url: sUrl, param: JSON.stringify(linkData2), success: function (responseData) {
                            if (!responseData.header.errorMessageProcessed) {
                                comboStore2 = new Ext.data.Store({
                                    fields: ['cd', 'cdNm'],
                                    data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tbl
                                });
                            }
                        }
                    }
                    // 결재조건상태코드콤보로딩
                    , {
                        url: sUrl, param: JSON.stringify(linkData3), success: function (responseData) {
                            if (!responseData.header.errorMessageProcessed) {
                                comboStore3 = new Ext.data.Store({
                                    fields: ['cd', 'cdNm'],
                                    data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tbl
                                });
                            }
                        }
                    }
                ], {
                    success: function () {
                        /* ------------------------------------------------------------ */
                        that.PWF507SingleGrid = new ExtGrid({
                            /* ------------------------------------------------------------ */
                            // 단일탭 그리드 컬럼 정의
                            fields: ['No', 'aprvlCndNbr', 'srvcCd', 'srvcNm', 'aprvlRsnCd', 'aprvlPtrnDscd', 'aprvlTmpltId', 'stsCd']
                            , id: 'PWF507SingleGrid'
                            , columns: [
                                {
                                    text: 'No.'
                                    , dataIndex: 'rowIndex'
                                    , sortable: false
                                    , width: 30
                                    , style: 'text-align:center', align: 'right'
                                    // other config you need....
                                    , renderer: function (value, metaData, record, rowIndex, colIndex, sotre) {
                                    return rowIndex + 1;
                                }
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#aprvlCndNbr'),
                                    width: 120,
                                    dataIndex: 'aprvlCndNbr',
                                    editor: 'textfield',
                                    style: 'text-align:center',
                                    align: 'left'
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#srvcCd'),
                                    width: 100,
                                    dataIndex: 'srvcCd',
                                    editor: 'textfield',
                                    style: 'text-align:center',
                                    align: 'left'
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#srvcNm'),
                                    width: 170,
                                    dataIndex: 'srvcNm',
                                    editor: 'textfield',
                                    style: 'text-align:center'
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#aprvlRsnCd'),
                                    width: 130,
                                    dataIndex: 'aprvlRsnCd',
                                    style: 'text-align:center',
                                    align: 'left'
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore1
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore1.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore1.getAt(index).data;
                                            return rs.cdNm
                                        }
                                    } // end of render
                                } // end of aprvlRsnCd
                                , {
                                    text: bxMsg('cbb_items.AT#aprvlPtrnDscd'),
                                    width: 120,
                                    dataIndex: 'aprvlPtrnDscd',
                                    style: 'text-align:center',
                                    align: 'left'
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore2
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore2.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore2.getAt(index).data;
                                            return rs.cdNm
                                        }
                                    } // end of render
                                } // end of aprvlPtrnDscd
                                , {
                                    text: bxMsg('cbb_items.AT#aprvlTmpltId'),
                                    width: 200,
                                    dataIndex: 'aprvlTmpltId',
                                    editor: 'textfield',
                                    style: 'text-align:center'
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#stsCd'),
                                    width: 120,
                                    dataIndex: 'stsCd',
                                    style: 'text-align:center',
                                    align: 'left'
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore3
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore3.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore3.getAt(index).data;
                                            return rs.cdNm
                                        }
                                    } // end of render
                                } // end of stsCd
                            ] // end of columns
                            , listeners: {
                                dblclick: {
                                    element: 'body',
                                    fn: function () {
                                        /**
                                         * @type            - 'open-conts-page' 이벤트는 페이지 이동 이벤트 ('libs/bx/bx-frame/views/workspace.js' 에서 처리)
                                         * @pageHandler     - 이동할 페이지 핸들러명 ('scripts/views/main.js'의 pageSrcMap 참고)
                                         * @pageDPName      - 새로 추가될 탭 명
                                         * @pageInitialize  - 페이지 초기화 여부
                                         * @pageRenderInfo  - 초기화할때 전달할 인자, ('scripts/views/test/excel-test/_excel-test.js' 의 initialize 메소드 참고)
                                         */
                                        var selectedRecord = that.PWF507SingleGrid.grid.getSelectionModel().selected.items[0];
                                        if (!selectedRecord) {
                                            return;
                                        } else {
                                            var aprvlCndNbr = selectedRecord.data.aprvlCndNbr;


                                            that.$el.trigger({
                                                type: 'open-conts-page',
                                                pageHandler: 'PWF508',
                                                pageDPName: bxMsg('cbb_items.SCRN#PWF508'),
                                                pageInitialize: true,
                                                pageRenderInfo: {
                                                    aprvlCndNbr: aprvlCndNbr
                                                    , aprvlCndDstnctnCd: "02"
                                                }
                                            });
                                        }
                                    }
                                }
                            }




                        });
                        // 단일탭 그리드 렌더
                        that.createGrid("single");


                    } // end of success:.function
                }); // end of bxProxy.all


            } // end of initialize:


            // 첫번째 탭 활성화 설정
            , render: function () {
                this.currentSubTab = 'PWF507-single-tab';
                return this.$el;
            }


            // 그리드 생성
            , createGrid: function (target) {
                if (target == "single") {
                    this.$el.find(".PWF507-single-grid").html(this.PWF507SingleGrid.render({'height': CgridHeight}));
                }
            } // end of createGrid


            // 탭 변경 이벤트 처리
            , changeTab: function (e) {
                var $clickedTab = $(e.currentTarget),
                    pageLink = $clickedTab.attr('data-link'),
                    $tabs = $clickedTab.siblings('.bx-tab-menu-item'),
                    $pages = $clickedTab.parents('.bx-tab-menu').next().find('.bx-tab-page');


                // 활성화 되어있는 탭과 페이지 비활성화 처리
                $tabs.filter('.is-active').removeClass('is-active');
                $pages.filter('.is-active').removeClass('is-active');


                // 클릭된 탭과 페이지 활성화 처리
                $clickedTab.addClass('is-active');
                $pages.filter('[data-link="' + pageLink + '"]').addClass('is-active');


                // 현재 활성화 탭 설정
                this.currentSubTab = pageLink;
                $pages.filter('[data-link="' + pageLink + '"]').show();




                // 탭에 연결된 메소드 호출
                this.renderSubPage();
            }


            // 텝에 연결된 매소드 호출
            , renderSubPage: function (param) {
                var subPageRenderName = this.subPageRenderMap[this.currentSubTab];


                // 기본부에서 넘어온 파라미터를 현재창의 전역변수에 넣는다
                this.settedParam = param;


                (typeof this[subPageRenderName] === 'function') && this[subPageRenderName]();
            }


            //결재조건상세 페이지 열기
            , addPWFList: function (param) {
                this.$el.trigger({
                    type: 'open-conts-page',
                    pageHandler: 'PWF508',
                    pageDPName: bxMsg('cbb_items.SCRN#PWF508'),
                    pageInitialize: true,
                    pageRenderInfo: {
                        aprvlCndNbr: "add"
                    }
                });
            }


            // 그리드의 날짜컬럼의 포맷변경 yyyymmdd ==> yyyy-mm-dd
            , setGridDate: function (val) {
                var now = new Date(val);
                var returnVal = val;


                if (isNaN(now.getFullYear())) {
                    if (val.length == 8) {
                        val = val.substring(0, 4) + "-" + val.substring(4, 6) + "-" + val.substring(6, 8);
                    }
                    returnVal = val;
                }
                else {
                    var year = now.getFullYear();
                    var month = now.getMonth() + 1;
                    var date = now.getDate();


                    if ((month + "").length < 2) {
                        month = "0" + month;   //달의 숫자가 1자리면 앞에 0을 붙임.
                    }
                    if ((date + "").length < 2) {
                        date = "0" + date;
                    }
                    returnVal = year + "-" + Month + "-" + date;
                }
                return returnVal;
            }


            // 그리드의 날짜컬럼의 포맷 변경 yyyy-mm-dd ==> yyyymmdd
            , getGridDate: function (val) {
                var now = new Date(val);
                var returnVal;
                if (isNaN(now.getFullYear())) {
                    returnVal = val;
                }
                else {
                    var year = now.getFullYear();
                    var month = now.getMonth() + 1;
                    var date = now.getDate();


                    if ((month + "").length < 2) {
                        month = "0" + month;   //달의 숫자가 1자리면 앞에 0을 붙임.
                    }
                    if ((date + "").length < 2) {
                        date = "0" + date;
                    }


                    returnVal = year + "" + month + "" + date;
                }
                return returnVal;
            }




            /* ============================================================== */
            /*  Single 조회         */
            /* ============================================================== */
            , selSingle: function () {
                chkAddcol = false;
                var that = this;
                var sParam = {};
                var param = this.settedParam;


                // 입력 Key값 set
                sParam.aprvlRsnCd = param.aprvlRsnCd;  // 결재사유코드
                sParam.aprvlPtrnDscd = param.aprvlPtrnDscd;  // 결재패턴구분코드
                sParam.aprvlTmpltId = param.aprvlTmpltId;  // 워크플로우식별자
                sParam.cmpntCd = param.cmpntCd;  // 컴포넌트코드
                sParam.srvcCd = param.srvcCd;  // 서비스코드
                sParam.instCd = param.instCd; // 기관코드


                var linkData = {"header": fn_getHeader("PWF4018401"), "AprvlCndMgmtSvcGetAprvlCndListIn": sParam};


                // ajax호출
                bxProxy.post(sUrl, JSON.stringify(linkData), {
                    //loading 설정
                    enableLoading: true,
                    success: function (responseData) {
                        if (fn_commonChekResult(responseData)) {
                            var tbList = responseData.AprvlCndMgmtSvcGetAprvlCndListOut.cndList;
                            if (tbList != null || tbList.length > 0) {
                                that.PWF507SingleGrid.setData(tbList);
                            }
                            else {
                                that.PWF507SingleGrid.resetData();
                            }
                        }
                    }   // end of suucess: fucntion
                });     // end of bxProxy
            } // end of 조회
        }); // end of PWF507TabView = Backbone.View.extend


        return PWF507TabView;
    }  // end of main function
);
