// Generated by  on 2015-01-27 오후 5:15:30
define(
  [
      'bx/common/config'
      ,'bx-component/message/message-alert'
      ,'bx-component/message/message-confirm'
      ,'bx-component/ext-grid/_ext-grid'
      ,'text!app/views/page/PWF/030/PWF030-list-tpl.html'
      ,'app/views/page/popup/CAPCM/popup-message'
  ],
  function (
      config,
      alertMessage,
      confirmMessage,
      ExtGrid,
      tpl,
      PopupMessage
  ) {


      var PWFTabView = Backbone.View.extend({


          // 태그이름 설정
          tagName: 'section',


          // 클래스 이름 설정
          className: 'PWF030-list-page',


          // 템플릿 설정
          templates: {
              'tpl': tpl
          }


          // 이벤트 설정
          ,events: {
              'click.bx-tab-container .bx-tab-menu-item': 'changeTab'
          }


          // 탭에 따라 호출될 메소드 지정
          ,subPageRenderMap: {
              'PWF030-content-tab': 'fn_contentTab'
        	  , 'PWF030-involved-tab': 'fn_involvedTab'
    		  , 'PWF030-related-tab': 'fn_relatedTab'
          }


          ,initialize: function (initData) {
              var that = this;


              $.extend(that,initData);


              // 페이지 템플릿 설정
              that.$el.html(that.tpl());


      } // end of initialize:


      // 첫번째 탭 활성화 설정
      ,render: function() {
          this.currentSubTab = 'PWF030-content-tab';
          return this.$el;
      }


      // 탭 변경 이벤트 처리
      ,changeTab: function(e) {
          var $clickedTab = $(e.currentTarget),
          pageLink = $clickedTab.attr('data-link'),
          $tabs = $clickedTab.siblings('.bx-tab-menu-item'),
          $pages = $clickedTab.parents('.bx-tab-menu').next().find('.bx-tab-page');


          // 활성화 되어있는 탭과 페이지 비활성화 처리
          $tabs.filter('.is-active').removeClass('is-active');
          $pages.filter('.is-active').removeClass('is-active');


          // 클릭된 탭과 페이지 활성화 처리
          $clickedTab.addClass('is-active');
          $pages.filter('[data-link="'+pageLink+'"]').addClass('is-active');


          // 현재 활성화 탭 설정
          this.currentSubTab = pageLink;
          $pages.filter('[data-link="'+pageLink+'"]').show();


          // 탭에 연결된 메소드 호출
          this.renderSubPage();
      }


      // 텝에 연결된 매소드 호출
      , renderSubPage: function(param) {
          var subPageRenderName = this.subPageRenderMap[this.currentSubTab];
          //info 에서 넘어온 파라미터를 전역변수에 현재 창의 전역변후에 넣는다.
          this.settedParam = param; 


          (typeof this[subPageRenderName] === 'function') && this[subPageRenderName]();
      }


      //첫번째 텝 선택
      , fn_contentTab : function() {
    	  console.info("fn_contentTab");
      }


      //두번째 텝 선택
      , fn_involvedTab : function() {
    	  console.info("fn_involvedTab");
      }


      //세번째텝 선택
      , fn_relatedTab : function() {
    	  console.info("fn_relatedTab");
      }


      }); // end of PWFTabView = Backbone.View.extend


      return PWFTabView;
  }  // end of main function
);
