// Generated by Bankware Global CBB Solution Center on 2015-02-04 오전 12:48:27


define(
    [
         'bx/common/config'
         ,'bx-component/message/message-alert'
         ,'bx-component/message/message-confirm'
         ,'bx-component/date-picker/_date-picker'
         ,'text!app/views/page/PWF/507/PWF507-base-tpl.html'
         ,'app/views/page/popup/CAPCM/popup-aprvlTmplt'
         ,'bx/common/common-info'
   ],
   function (
         config
         , alertMessage
         , confirmMessage
         , DatePicker
         , tpl
         , PopupAprvlTmplt
         , commonInfo
   ){
    	 var instCdBase = "";


         var PWF507BaseView = Backbone.View.extend({
               // 태그이름 설정
               tagName: 'section',
               // 클래스이름 설정
               className: 'PWF507-base-page',
               // 탬플릿 설정
               templates: {
                   'tpl': tpl
               }
               // 이벤트 설정
               , events: {
                   'click .PWF507-select-btn': 'selectPWF507Base'
                   ,'click #aprvlTmpltIdPop': 'popUpBrowseWflowId'
               }


               , initialize: function (initData) {
                   var that = this;
                   var initFlag = true;


                   // initData 저장
                   $.extend(that, initData);


                   // 페이지 템플릿 설정
                   that.$el.html(that.tpl());
               }


               , render: function() {
                   var that = this;


                   // 콤보데이터 로딩
                   var sParam = {};
                   var selectStyle = {};


                   //결재사유코드
                   sParam = {};
                   selectStyle = {};
                   sParam.className = "PWF507-aprvlRsnCd-wrap";
                   sParam.targetId = "aprvlRsnCd";
                   sParam.nullYn = "Y";
                   sParam.cdNbr = "12303";
                   fn_getCodeList(sParam, this, selectStyle);


                   //결재패턴구분코드
                   sParam = {};
                   selectStyle = {};
                   sParam.className = "PWF507-aprvlPtrnDscd-wrap";
                   sParam.targetId = "aprvlPtrnDscd";
                   sParam.nullYn = "Y";
                   sParam.cdNbr = "12302";
                   fn_getCodeList(sParam, this, selectStyle);




                   // 날짜타입 컬럼 초기화


                   // 기본부 초기화 
                   this.setPWF507BaseData(this, "", "X");


                   return this.$el;
               }


               /* ======================================================================== */
               // 입출력항목 setting
               /* ======================================================================== */
               , setPWF507BaseData: function(that, responseData, type) {
                   that = this;


                   if(type == "X") {  // 초기화                      
                       that.$el.find('[data-form-param="aprvlRsnCd"] option:eq(0)').attr("selected", "selected");       //결재사유코드
                       that.$el.find('[data-form-param="aprvlPtrnDscd"] option:eq(0)').attr("selected", "selected");       //결재패턴구분코드
                       that.$el.find('[data-form-param="aprvlTmpltId"]').val("");       //결재탬플릿식별자
                       that.$el.find('[data-form-param="cmpntCd"]').val("");       //컴포넌트코드
                       that.$el.find('[data-form-param="srvcCd"]').val("");       //서비스코드
                   }
                   else {                       
                       that.$el.find('[data-form-param="aprvlRsnCd"]').val(responseData.aprvlRsnCd);       //결재사유코드
                       that.$el.find('[data-form-param="aprvlPtrnDscd"]').val(responseData.aprvlPtrnDscd);       //결재패턴구분코드
                       that.$el.find('[data-form-param="aprvlTmpltId"]').val(responseData.aprvlTmpltId);       //결재탬플릿식별자
                       that.$el.find('[data-form-param="cmpntCd"]').val(responseData.cmpntCd);       //컴포넌트코드
                       that.$el.find('[data-form-param="srvcCd"]').val(responseData.srvcCd);       //서비스코드
                   }
              }


               //tree 선택시 이벤트 발생
               , setTreeData : function(param) {
            	   this.$el.find('[data-form-param="cmpntCd"]').val(param.cmpntCd);       //컴포넌트코드
                   this.$el.find('[data-form-param="srvcCd"]').val(param.srvcCd);       //서비스코드            	   
               }


               /* ======================================================================== */
               /*    목록조회  팝업     테스트                                */
               /* ======================================================================== */
                , popUpBrowseWflowId: function() {
            	   var that = this;
               	   var param = {};
               	   var instInfo = commonInfo.getInstInfo();
	        	   instCdBase = instInfo.instCd;


	        	   param.instCd = instCdBase;


                   var popupAprvlTmplt = new PopupAprvlTmplt(param); // 팝업생성
                   popupAprvlTmplt.render();


                   popupAprvlTmplt.on('popUpSetData', function(param) {
                       that.$el.find('[data-form-param="aprvlTmpltId"]').val(param.aprvlTmpltId); // 프로세스식별자
//                       that.$el.find('[data-form-param="aprvlTmpltId"]').prop("disabled", true);
//                       that.$el.find('[data-form-param="wflowNm"]').val(param.wflownm); // 프로세스명
                   });
                }


               /* ======================================================================== */
               /*    Click select btn                                                      */
               /* ======================================================================== */
               , selectPWF507Base: function () {
                   var that = this;
                   var param = {};
   	        	   var instInfo = commonInfo.getInstInfo();
   	        	   instCdBase = instInfo.instCd;


                   if (!instCdBase ) {
                       alertMessage.info(bxMsg('cbb_items.SCRNITM#instSearchMsg'));


                       return;
                   }


                   // 조회 key값 set
   	        	   param.instCd = instCdBase;
                   param.aprvlRsnCd = this.$el.find('[data-form-param="aprvlRsnCd"]').val(); // 결재사유코드
                   param.aprvlPtrnDscd = this.$el.find('[data-form-param="aprvlPtrnDscd"]').val(); // 결재패턴구분코드
                   param.aprvlTmpltId = this.$el.find('[data-form-param="aprvlTmpltId"]').val(); // 결재탬플릿식별자
                   this.$el.find('[data-form-param="aprvlTmpltId"]').prop("disabled", true);
                   param.cmpntCd = this.$el.find('[data-form-param="cmpntCd"]').val(); // 컴포넌트코드
                   param.srvcCd = this.$el.find('[data-form-param="srvcCd"]').val(); // 서비스코드
                   param.aprvlCndDstnctnCd = "01";


                   that.trigger('loadData', param);


               } // end of select function


        }); // end of Backbone.View.extend({


       return PWF507BaseView;


     } // end of define function
); // end of define
