// Generated by Bankware Global CBB Solution Center on 2015-02-04 오후 2:06:12


define(
  [
		'bx/common/config',
		'text!app/views/page/PWF/100/_PWF100.html'
  ],
  function (
		  config,
		  tpl
  ) {
      var PWF100View = Backbone.View.extend({


          // 태그이름 설정
          tagName: 'section'


          // 클래스이름 설정
          ,className: 'bx-container bxp-PWF100-page'


          // 템플릿 설정
          ,templates: {
              'tpl': tpl
          }


          ,initialize: function (initData) {
              var that = this;


              $.extend(that, initData);


              // 페이지 템플릿 설정
              that.$el.html(that.tpl());


              var url = baseUrl + '/activiti-explorer/ui/1/loginHandler';
              var linkData = 'username=00000000&password=12345';
              var requestOption = {
                      type: 'post',
                      url: url,
                      cache: false,
                      data: linkData
              };


              $.ajax(url, requestOption);


              that.$el.find('#scaled-frame-workflow').attr('src', baseUrl + '/activiti-explorer/#processmodel');
          } // end of initialize


          ,render: function() {
        	  var that = this;


              return this.$el;
          }, // end of render
      });// Backbone.View.extend


      return PWF100View;


  } // end of function
);
