// Generated by Bankware Global CBB Solution Center on 2015-02-03 오후 3:26:10


define(
    [
        'bx/common/config'
        , 'bx-component/message/message-alert'
        , 'bx-component/message/message-confirm'
        , 'bx-component/date-picker/_date-picker'
        , 'text!app/views/page/PWF/508/PWF508-base-tpl.html'
        , 'app/views/page/popup/popup-srvc'
        , 'app/views/page/popup/CAPCM/popup-aprvlTmplt'
        , 'app/views/page/popup/popup-brnchCd'
        , 'bx/common/common-info'
        , 'bx/common/common-message'
    ],
    function (config
        , alertMessage
        , confirmMessage
        , DatePicker
        , tpl
        , PopupSrvcCd
        , PopupAprvlTmplt
        , PopupBrnchCd
        , commonInfo) {
        var initParam = "";
        var initFlag = true;


        var bizDscd = "";
        var pdTpCd = "";
        var pdTmpltCd = "";
        var pdCd = "";


        var comboBoxCount = 0;


        var PWF508BaseView = Backbone.View.extend({
            // 태그이름 설정
            tagName: 'section',
            // 클래스이름 설정
            className: 'PWF508-base-page',
            // 탬플릿 설정
            templates: {
                'tpl': tpl
            }
            // 이벤트 설정
            , events: {
                'click .PWF508-reset-btn': 'resetPWF508Base'
                , 'click .PWF508-select-btn': 'selectPWF508Base'
                , 'click .PWF508-save-btn': 'savePWF508Base'
                , 'click .PWF508-delete-btn': 'deletePWF508Base'
                , 'change .amtCndYn': 'fn_amtCndYnCheck'
                , 'change .crncyCdCndYn': 'fn_crncyCdCndYnCheck'
                , 'change .txHmsCndYn': 'fn_txHmsCndYnCheck'
                , 'change .txBrnchDscdCndYn': 'fn_txBrnchDscdCndYnCheck'
                , 'change .txBrnchCndYn': 'fn_txBrnchCndYnCheck'
                , 'change .pdCndYn': 'fn_pdClCndYnCheck'
                , 'change .PWF508-bizDscd-wrap': 'changeBizDscd'
                , 'change .PWF508-pdTpCd-wrap': 'changePdTpCd'
                , 'change .PWF508-pdTmpltCd-wrap': 'changePdTmpltCd'
                , 'change .PWF508-pdCd-wrap': 'changePdCd'
                , 'click #srvcCdPop': 'fn_popupSrvcCd'
                , 'click #aprvlTmpltIdPop': 'fn_popupAprvlId'
                , 'click #brnchCdPop': 'fn_popupBrnchCd'
            }


            , initialize: function (initData) {
                var that = this;
                initFlag = true;
                 


                // initData 저장
                $.extend(that, initData);


                // 페이지 템플릿 설정
                that.$el.html(that.tpl());


                if (initData != null || initData != "") {
                    initParam = "";
                    initParam = initData.aprvlCndNbr;
                }
            }


            , render: function () {
                var that = this;
                // 데이터 피커 로드
                this.loadDatePicker();


                // 콤보데이터 로딩
                var sParam = {};
                var selectStyle = {};


                //결재패턴구분코드
                sParam = {};
                selectStyle = {};
                sParam.className = "PWF508-aprvlPtrnDscd-wrap";
                sParam.targetId = "aprvlPtrnDscd";
                sParam.nullYn = "Y";
                sParam.cdNbr = "12302";
                fn_getCodeList(sParam, this, selectStyle, that.countCombobox.bind(that));


                //결재조건상태코드
                sParam = {};
                selectStyle = {};
                sParam.className = "PWF508-stsCd-wrap";
                sParam.targetId = "stsCd";
                sParam.nullYn = "Y";
                sParam.cdNbr = "12307";
                fn_getCodeList(sParam, this, selectStyle, that.countCombobox.bind(that));


                //결재사유코드
                sParam = {};
                selectStyle = {};
                sParam.className = "PWF508-aprvlRsnCd-wrap";
                sParam.targetId = "aprvlRsnCd";
                sParam.nullYn = "Y";
                sParam.cdNbr = "12303";
                fn_getCodeList(sParam, this, selectStyle, that.countCombobox.bind(that));


                //금액유형코드
                sParam = {};
                selectStyle = {};
                sParam.className = "PWF508-amtTpCd-wrap";
                sParam.targetId = "amtTpCd";
                sParam.nullYn = "Y";
                sParam.cdNbr = "50026";
                sParam.disabled = true;
                fn_getCodeList(sParam, this, selectStyle, that.countCombobox.bind(that));


                //통화코드
                sParam = {};
                selectStyle = {};
                sParam.className = "PWF508-crncyCd-wrap";
                sParam.targetId = "crncyCd";
                sParam.nullYn = "Y";
                sParam.cdNbr = "T0001";
                sParam.disabled = true;
                fn_getCodeList(sParam, this, selectStyle, that.countCombobox.bind(that));


                //거래부점구분코드
                sParam = {};
                selectStyle = {};
                sParam.className = "PWF508-txBrnchDscd-wrap";
                sParam.targetId = "txBrnchDscd";
                sParam.nullYn = "Y";
                sParam.cdNbr = "12305";
                sParam.disabled = true;
                fn_getCodeList(sParam, this, selectStyle, that.countCombobox.bind(that));


                //업무구분코드
                sParam = {};
                selectStyle = {};
                sParam.className = "PWF508-bizDscd-wrap";
                sParam.targetId = "bizDscd";
                sParam.nullYn = "Y";
                sParam.cdNbr = "80015";
                sParam.disabled = true;
                fn_getCodeList(sParam, this, selectStyle, that.countCombobox.bind(that));


                // 날짜타입 컬럼 초기화
                var aplyStartDt = this.subViews['aplyStartDt'].getValue();
                if (aplyStartDt == null || aplyStartDt == "") {
                    this.subViews['aplyStartDt'].setValue(getCurrentDate("yyyy-mm-dd"));
                }


                var aplyEndDt = this.subViews['aplyEndDt'].getValue();
                if (aplyEndDt == null || aplyEndDt == "") {
                    this.subViews['aplyEndDt'].setValue(getCurrentDate("yyyy-mm-dd"));
                }


                //initParam == add: 추가된 페이지
                //initParam == seqNbr: 조회된 페이지
                if (initParam != "" && initParam != "add") {
                    var that = this;


                    this.$el.find('[data-form-param="aprvlCndNbr"]').val(initParam);


                    //setTimeout(function () {
                    //    that.selectPWF508Base();
                    //}, 1000);
                } else {
                    //상품코드 초기화
                    that.initPdTpCd();
                    that.initPdTmpltCd();
                    that.initPdCd();


                    // 기본부 초기화
                    that.setPWF508BaseData(this, "", "X");
                }


                return this.$el;
            }


            , countCombobox: function () {
                var that = this;


                comboBoxCount += 1;


                if(comboBoxCount == 7) {
                	if(!fn_isEmpty(that.$el.find('[data-form-param="aprvlCndNbr"]').val())) {
                		that.selectPWF508Base();
                	}	
                }
            }


            /* ======================================================================== */
            // 입출력항목 setting
            /* ======================================================================== */
            , setPWF508BaseData: function (that, responseData, type) {
                var that = this;


                if (type == "X") {  // 초기화
                    that.$el.find('[data-form-param="aprvlCndNbr"]').val("");       //결재조건번호
                    //that.$el.find('[data-form-param="aprvlCndNbr"]').prop("disabled", false);
                    that.subViews['aplyStartDt'].setValue(getCurrentDate("yyyy-mm-dd"));     //적용시작년월일
                    that.subViews['aplyEndDt'].setValue("9999-12-31");     //적용종료년월일
                    that.$el.find('[data-form-param="srvcCd"]').val("");
                    that.$el.find('[data-form-param="srvcCd"]').prop("disabled", false); //서비스코드
                    that.$el.find('[data-form-param="srvcNm"]').val("");
                    that.$el.find('[data-form-param="aprvlPtrnDscd"]').val("");       //결재패턴구분코드
                    that.$el.find('[data-form-param="stsCd"]').val('1');//결재조건상태코드
                    that.$el.find('[data-form-param="stsCd"]').prop("disabled", false);//결재조건상태코드
                    that.$el.find('[data-form-param="aprvlTmpltId"]').val("");       //결재탬플릿식별자
                    that.$el.find('[data-form-param="aprvlRsnCd"]').val("");//결재사유코드
                    that.$el.find('[data-form-param="aprvlRsnCd"]').prop("disabled", false);//결재사유코드


                    //금액조건여부 초기화시 체크해제 및 코드 비활성화
                    that.$el.find('[data-form-param="amtCndYn"]').val("N");       //금액조건여부
                    that.$el.find('[data-form-param="amtCndYn"]').prop("checked", false);
                    that.$el.find('[data-form-param="amtTpCd"]').val("");
                    that.$el.find('[data-form-param="amtTpCd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="amtCndMinVal"]').val(0);
                    that.$el.find('[data-form-param="amtCndMaxVal"]').val(0);


                    //통화코드조건여부 초기화시 체크해제 및 코드 비활성화
                    that.$el.find('[data-form-param="crncyCdCndYn"]').val("N");       //통화코드조건여부
                    that.$el.find('[data-form-param="crncyCdCndYn"]').prop("checked", false);
                    that.$el.find('[data-form-param="crncyCd"]').val("");
                    that.$el.find('[data-form-param="crncyCd"]').prop("disabled", true);


                    //거래시각조건여부 초기화시 체크해제 및 코드 비활성화
                    that.$el.find('[data-form-param="txHmsCndYn"]').val("N");       //거래시각조건여부
                    that.$el.find('[data-form-param="txHmsCndYn"]').prop("checked", false);
                    that.$el.find('[data-form-param="txStartHms"]').val("00:00");
                    that.$el.find('[data-form-param="txStartHms"]').prop("disabled", true);
                    that.$el.find('[data-form-param="txEndHms"]').val("00:00");
                    that.$el.find('[data-form-param="txEndHms"]').prop("disabled", true);


                    //거래부점구분조건여부 초기화시 체크해제 및 코드 비활성화
                    that.$el.find('[data-form-param="txBrnchDscdCndYn"]').val("N");       //거래부점구분조건여부
                    that.$el.find('[data-form-param="txBrnchDscdCndYn"]').prop("checked", false);
                    that.$el.find('[data-form-param="txBrnchDscd"]').val("");
                    that.$el.find('[data-form-param="txBrnchDscd"]').prop("disabled", true);


                    //거래부점조건여부 초기화시 체크해제 및 코드 비활성화
                    that.$el.find('[data-form-param="txBrnchCndYn"]').val("N");       //거래부점조건여부
                    that.$el.find('[data-form-param="txBrnchCndYn"]').prop("checked", false);
                    that.$el.find('[data-form-param="txBrnchCd"]').val("");
                    that.$el.find('[data-form-param="txBrnchCd"]').prop("disabled", true);


                    //상품분류조건여부 초기화시 체크해제 및 코드 비활성화
                    that.$el.find('[data-form-param="pdCndYn"]').val("N");       //상품분류조건여부
                    that.$el.find('[data-form-param="pdCndYn"]').prop("checked", false);
                    that.$el.find('[data-form-param="bizDscd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="pdTpCd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="pdTmpltCd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="pdCd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="bizDscd"]').val("");       //업무구분코드
                    that.$el.find('[data-form-param="pdTpCd"]').val("");       //상품유형코드
                    that.$el.find('[data-form-param="pdTmpltCd"]').val("");       //상품템플릿코드
                    that.$el.find('[data-form-param="pdCd"]').val("");       //상품코드
                }
                else if (type == "P") {
                    that.$el.find('[data-form-param="bizDscd"]').val(bizDscd);       //업무구분코드
                    that.$el.find('[data-form-param="pdTpCd"]').val(pdTpCd);       //상품유형코드
                    that.$el.find('[data-form-param="pdTmpltCd"]').val(pdTmpltCd);       //상품템플릿코드
                    that.$el.find('[data-form-param="pdCd"]').val(pdCd);       //상품코드
                    that.$el.find('[data-form-param="pdNm"]').val(pdNm);       //상품명
                }
                else {
                    that.$el.find('[data-form-param="aprvlCndNbr"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.aprvlCndNbr);       //결재조건번호
                    //that.$el.find('[data-form-param="aprvlCndNbr"]').prop("disabled", false);//결재조건번호 disabled
                    that.subViews['aplyStartDt'].setValue(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.aplyStartDt);     //적용시작년월일
                    that.subViews['aplyEndDt'].setValue(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.aplyEndDt);     //적용종료년월일
                    that.$el.find('[data-form-param="srvcCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.srvcCd); //서비스코드
                    that.$el.find('[data-form-param="srvcNm"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.srvcNm); //서비스명
                    that.$el.find('[data-form-param="aprvlPtrnDscd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.aprvlPtrnDscd);       //결재패턴구분코드
                    that.$el.find('[data-form-param="stsCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.stsCd);//결재조건상태코드
                    that.$el.find('[data-form-param="aprvlTmpltId"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.aprvlTmpltId);       //결재탬플릿식별자
                    that.$el.find('[data-form-param="aprvlTmpltNm"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.aprvlTmpltNm);       //워크플로우명
                    that.$el.find('[data-form-param="aprvlRsnCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.aprvlRsnCd);//결재사유코드


                    that.$el.find('[data-form-param="amtCndYn"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.amtCndYn); //금액조건여부
                    that.$el.find('[data-form-param="crncyCdCndYn"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.crncyCdCndYn);       //통화코드조건여부
                    that.$el.find('[data-form-param="txHmsCndYn"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.txHmsCndYn);//거래시각조건여부
                    that.$el.find('[data-form-param="txBrnchDscdCndYn"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.txBrnchDscdCndYn);       //거래부점구분조건여부
                    that.$el.find('[data-form-param="txBrnchCndYn"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.txBrnchCndYn);//거래부점조건여부
                    that.$el.find('[data-form-param="pdCndYn"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.pdCndYn);//상품분류코드여부


                    if (that.$el.find('[data-form-param="amtCndYn"]').val() == "Y") {
                        that.$el.find('[data-form-param="amtCndYn"]').prop("checked", true);
                        that.$el.find('[data-form-param="amtTpCd"]').prop("disabled", false);
                        that.$el.find('[data-form-param="amtCndMinVal"]').prop("disabled", false);
                        that.$el.find('[data-form-param="amtCndMaxVal"]').prop("disabled", false);
                        that.$el.find('[data-form-param="amtTpCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.amtTpCd);       //금액유형코드
                        that.$el.find('[data-form-param="amtCndMinVal"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.amtCndMinVal);
                        that.$el.find('[data-form-param="amtCndMaxVal"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.amtCndMaxVal);
                    } else {
                        that.$el.find('[data-form-param="amtCndYn"]').prop("checked", false);
                        that.$el.find('[data-form-param="amtTpCd"]').prop("disabled", true);
                        that.$el.find('[data-form-param="amtCndMinVal"]').prop("disabled", true);
                        that.$el.find('[data-form-param="amtCndMaxVal"]').prop("disabled", true);
                    }//금액조건여부


                    if (that.$el.find('[data-form-param="crncyCdCndYn"]').val() == "Y") {
                        that.$el.find('[data-form-param="crncyCdCndYn"]').prop("checked", true);
                        that.$el.find('[data-form-param="crncyCd"]').prop("disabled", false);
                        that.$el.find('[data-form-param="crncyCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.crncyCd);       //통화코드
                    } else {
                        that.$el.find('[data-form-param="crncyCdCndYn"]').prop("checked", false);
                        that.$el.find('[data-form-param="crncyCd"]').prop("disabled", true);
                    }//통화코드조건여부


                    if (that.$el.find('[data-form-param="txHmsCndYn"]').val() == "Y") {
                        that.$el.find('[data-form-param="txHmsCndYn"]').prop("checked", true);
                        that.$el.find('[data-form-param="txStartHms"]').prop("disabled", false);
                        that.$el.find('[data-form-param="txEndHms"]').prop("disabled", false);
                        that.$el.find('[data-form-param="txStartHms"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.txStartHms);       //거래시작시각
                        that.$el.find('[data-form-param="txEndHms"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.txEndHms);       //거래종료시각
                    } else {
                        that.$el.find('[data-form-param="txHmsCndYn"]').prop("checked", false);
                        that.$el.find('[data-form-param="txStartHms"]').prop("disabled", true);
                        that.$el.find('[data-form-param="txEndHms"]').prop("disabled", true);
                    }//거래시각조건여부


                    if (that.$el.find('[data-form-param="txBrnchDscdCndYn"]').val() == "Y") {
                        that.$el.find('[data-form-param="txBrnchDscdCndYn"]').prop("checked", true);
                        that.$el.find('[data-form-param="txBrnchDscd"]').prop("disabled", false);
                        that.$el.find('[data-form-param="txBrnchDscd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.txBrnchDscd);       //거래부점구분코드
                    } else {
                        that.$el.find('[data-form-param="txBrnchDscdCndYn"]').prop("checked", false);
                        that.$el.find('[data-form-param="txBrnchDscd"]').prop("disabled", true);
                    }//거래부점구분조건여부


                    if (that.$el.find('[data-form-param="txBrnchCndYn"]').val() == "Y") {
                        that.$el.find('[data-form-param="txBrnchCndYn"]').prop("checked", true);
                        that.$el.find('[data-form-param="txBrnchCd"]').prop("disabled", false);
                        that.$el.find('[data-form-param="txBrnchCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.txBrnchCd);       //거래부점코드
                    } else {
                        that.$el.find('[data-form-param="txBrnchCndYn"]').prop("checked", false);
                        that.$el.find('[data-form-param="txBrnchCd"]').prop("disabled", true);
                    }//거래부점조건여부


                    if (that.$el.find('[data-form-param="pdCndYn"]').val() == "Y") {
                        that.$el.find('[data-form-param="pdCndYn"]').prop("checked", true);
                        that.$el.find('[data-form-param="bizDscd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.bizDscd);       //상품대분류코드
                        that.$el.find('[data-form-param="pdTpCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.pdTpCd);       //상품중분류코드
                        that.$el.find('[data-form-param="pdTmpltCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.pdTmpltCd);       //상품템플릿코드
                        that.$el.find('[data-form-param="pdCd"]').val(responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.pdCd);       //상품코드


                        that.$el.find('[data-form-param="bizDscd"]').prop('disabled', false);
                        that.$el.find('[data-form-param="pdTpCd"]').prop('disabled', false);
                        that.$el.find('[data-form-param="pdTmpltCd"]').prop('disabled', false);
                        that.$el.find('[data-form-param="pdCd"]').prop('disabled', false);
                    } else {
                        //상품코드 초기화
                        that.initPdTpCd();
                        that.initPdTmpltCd();
                        that.initPdCd();
                        that.$el.find('[data-form-param="pdCndYn"]').prop("checked", false);
                        that.$el.find('[data-form-param="bizDscd"]').prop("disabled", true);       //업무구분코드
                        that.$el.find('[data-form-param="pdTpCd"]').prop("disabled", true);       //상품유형코드
                        that.$el.find('[data-form-param="pdTmpltCd"]').prop("disabled", true);       //상품템플릿코드
                        that.$el.find('[data-form-param="pdCd"]').prop("disabled", true);               //상품코드
                    }//상품분류코드여부
                }
            }
            /* ======================================================================== */
            /*    Click 금액조건여부 btn                                                       */
            /* ======================================================================== */
            , fn_amtCndYnCheck: function () {
                var that = this;
                if (that.$el.find('[data-form-param="amtCndYn"]').val() == "Y") {
                    that.$el.find('[data-form-param="amtCndYn"]').val("N");
                    that.$el.find('[data-form-param="amtTpCd"]').val("");
                    that.$el.find('[data-form-param="amtCndMinVal"]').val("");
                    that.$el.find('[data-form-param="amtCndMaxVal"]').val("");
                    that.$el.find('[data-form-param="amtTpCd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="amtCndMinVal"]').prop("disabled", true);
                    that.$el.find('[data-form-param="amtCndMaxVal"]').prop("disabled", true);
                } else if (that.$el.find('[data-form-param="amtCndYn"]').val() == "N") {
                    that.$el.find('[data-form-param="amtCndYn"]').val("Y");
                    that.$el.find('[data-form-param="amtTpCd"]').prop("disabled", false);
                    //that.$el.find('[data-form-param="amtCndMinVal"]').val("");
                    //that.$el.find('[data-form-param="amtCndMaxVal"]').val("");
                    that.$el.find('[data-form-param="amtCndMinVal"]').prop("disabled", false);
                    that.$el.find('[data-form-param="amtCndMaxVal"]').prop("disabled", false);
                }
            }


            /* ======================================================================== */
            /*    Click 통화코드조건여부 btn                                                       */
            /* ======================================================================== */
            , fn_crncyCdCndYnCheck: function () {
                var that = this;
                if (that.$el.find('[data-form-param="crncyCdCndYn"]').val() == "Y") {
                    that.$el.find('[data-form-param="crncyCdCndYn"]').val("N");
                    that.$el.find('[data-form-param="crncyCd"]').val("");
                    that.$el.find('[data-form-param="crncyCd"]').prop("disabled", true);
                } else if (that.$el.find('[data-form-param="crncyCdCndYn"]').val() == "N") {
                    that.$el.find('[data-form-param="crncyCdCndYn"]').val("Y");
                    that.$el.find('[data-form-param="crncyCd"]').prop("disabled", false);
                }
            }


            /* ======================================================================== */
            /*    Click 거래시각조건여부 btn                                                       */
            /* ======================================================================== */
            , fn_txHmsCndYnCheck: function () {
                var that = this;


                if (that.$el.find('[data-form-param="txHmsCndYn"]').val() == "Y") {
                    that.$el.find('[data-form-param="txHmsCndYn"]').val("N");
                    that.$el.find('[data-form-param="txStartHms"]').val("");
                    that.$el.find('[data-form-param="txStartHms"]').prop("disabled", true);
                    that.$el.find('[data-form-param="txEndHms"]').val("");
                    that.$el.find('[data-form-param="txEndHms"]').prop("disabled", true);
                } else if (that.$el.find('[data-form-param="txHmsCndYn"]').val() == "N") {
                    that.$el.find('[data-form-param="txHmsCndYn"]').val("Y");
                    that.$el.find('[data-form-param="txStartHms"]').prop("disabled", false);
                    that.$el.find('[data-form-param="txEndHms"]').prop("disabled", false);
                }
            }


            /* ======================================================================== */
            /*    Click 거래부점구분조건여부 btn                                                       */
            /* ======================================================================== */
            , fn_txBrnchDscdCndYnCheck: function () {
                var that = this;
                if (that.$el.find('[data-form-param="txBrnchDscdCndYn"]').val() == "Y") {
                    that.$el.find('[data-form-param="txBrnchDscdCndYn"]').val("N");
                    that.$el.find('[data-form-param="txBrnchDscd"]').val("");
                    that.$el.find('[data-form-param="txBrnchDscd"]').prop("disabled", true);
                } else if (that.$el.find('[data-form-param="txBrnchDscdCndYn"]').val() == "N") {
                    that.$el.find('[data-form-param="txBrnchDscdCndYn"]').val("Y");
                    that.$el.find('[data-form-param="txBrnchDscd"]').prop("disabled", false);
                }
            }


            /* ======================================================================== */
            /*    Click 거래부점조건여부 btn                                                       */
            /* ======================================================================== */
            , fn_txBrnchCndYnCheck: function () {
                var that = this;
                if (that.$el.find('[data-form-param="txBrnchCndYn"]').val() == "Y") {
                    that.$el.find('[data-form-param="txBrnchCndYn"]').val("N");
                    that.$el.find('[data-form-param="txBrnchCd"]').val("");
                    that.$el.find('[data-form-param="txBrnchCd"]').prop("disabled", true);
                } else if (that.$el.find('[data-form-param="txBrnchCndYn"]').val() == "N") {
                    that.$el.find('[data-form-param="txBrnchCndYn"]').val("Y");
                    that.$el.find('[data-form-param="txBrnchCd"]').prop("disabled", false);
                }
            }


            /* ======================================================================== */
            /*    Click 상품분류조건여부 btn                                                       */
            /* ======================================================================== */
            , fn_pdClCndYnCheck: function () {
                var that = this;
                if (that.$el.find('[data-form-param="pdCndYn"]').val() == "Y") {
                    that.$el.find('[data-form-param="pdCndYn"]').val("N");


                    that.$el.find('[data-form-param="bizDscd"]').val("");
                    that.$el.find('[data-form-param="pdTpCd"]').val("");
                    that.$el.find('[data-form-param="pdTmpltCd"]').val("");
                    that.$el.find('[data-form-param="pdCd"]').val("");


                    that.$el.find('[data-form-param="bizDscd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="pdTpCd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="pdTmpltCd"]').prop("disabled", true);
                    that.$el.find('[data-form-param="pdCd"]').prop("disabled", true);
                } else if (that.$el.find('[data-form-param="pdCndYn"]').val() == "N") {
                    that.$el.find('[data-form-param="pdCndYn"]').val("Y");
                    that.$el.find('[data-form-param="bizDscd"]').prop("disabled", false);
                    that.$el.find('[data-form-param="pdTpCd"]').prop("disabled", false);
                    that.$el.find('[data-form-param="pdTmpltCd"]').prop("disabled", false);
                    that.$el.find('[data-form-param="pdCd"]').prop("disabled", false);
                }
            }


            /* ======================================================================== */
            /*    Click reset btn                                                       */
            /* ======================================================================== */
            , resetPWF508Base: function (e) {
                initFlag = false;
                this.setPWF508BaseData(this, "", "X");
                this.$el.find('[data-form-param="aprvlCndNbr"]').focus();
                this.trigger('initList');
                //this.changeBizDscd();
            }


            /* ======================================================================== */
            /*    Click select btn                                                      */
            /* ======================================================================== */
            , selectPWF508Base: function () {
                var that = this;
                var sParam = {};
                initFlag = false;
                if (commonInfo.getInstInfo().instCd) {
                	sParam.instCd = commonInfo.getInstInfo().instCd;
                } else {
                    sParam.instCd = $.sessionStorage('headerInstCd');
                }


                instCdBase = sParam.instCd;


                // 조회 key값 set
                sParam.aprvlCndNbr = that.$el.find('[data-form-param="aprvlCndNbr"]').val();


                var linkData = {"header": fn_getHeader("PWF4028401"), "AprvlCndMgmtSvcGetAprvlCondDtlIn": sParam};


                //ajax 호출
                bxProxy.post(sUrl, JSON.stringify(linkData), {


                    success: function (responseData) {


                        // 에러여부 확인. 에러시 메시지 띄워주고 정상시 재조회 호출
                        if (fn_commonChekResult(responseData)) {
                            // 정상처리 메시지 출력
                            alertMessage.info(bxMsg('cbb_items.SCRNITM#success'));


                            // 기본부 항목 set
                            if (responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.bizDscd == "") {
                                that.setPWF508BaseData(that, responseData, "X");
                            } else {
                                bizDscd = "";
                                pdTpCd = "";
                                pdTmpltCd = "";
                                pdCd = "";


                                bizDscd = responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.bizDscd;
                                pdTpCd = responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.pdTpCd;
                                pdTmpltCd = responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.pdTmpltCd;
                                pdCd = responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.pdCd;


                                if (bizDscd != null && bizDscd != "") {
                                    //상품유형코드
                                    sParam = {};
                                    selectStyle = {};
                                    sParam.nullYn = "Y";
                                    sParam.targetId = "pdTpCd";
                                    sParam.className = "PWF508-pdTpCd-wrap";
                                    sParam.bizDscd = bizDscd;


                                    that.fn_PdList(sParam, that, selectStyle);
                                } else {
                                    that.initPdTpCd();
                                }


                                if (pdTpCd != null && pdTpCd != "") {
                                    //상품템플릿
                                    sParam = {};
                                    selectStyle = {};
                                    sParam.nullYn = "Y";
                                    sParam.targetId = "pdTmpltCd";
                                    sParam.className = "PWF508-pdTmpltCd-wrap";
                                    sParam.bizDscd = bizDscd;
                                    sParam.pdTpCd = pdTpCd;


                                    that.fn_PdList(sParam, that, selectStyle);
                                } else {
                                    that.initPdTmpltCd();
                                }


                                if (pdTmpltCd != null && pdTmpltCd != "") {
                                    //상품코드
                                    sParam = {};
                                    selectStyle = {};
                                    sParam.nullYn = "Y";
                                    sParam.targetId = "pdCd";
                                    sParam.className = "PWF508-pdCd-wrap";
                                    sParam.bizDscd = bizDscd;
                                    sParam.pdTpCd = pdTpCd;
                                    sParam.pdTmpltCd = pdTmpltCd;


                                    that.fn_PdList(sParam, that, selectStyle);
                                } else {
                                    that.initPdCd();
                                }


                                responseData.AprvlCndMgmtSvcGetAprvlCondDtlOut.aprvlCndNbr = that.$el.find('[data-form-param="aprvlCndNbr"]').val();


                                // 기본부 항목 set
                                that.setPWF508BaseData(that, responseData, "R");


                                // 첫번째 tab의 조회기능을 트리거하여 그리드도 처리함
                                var param = {};
                                param.instCd = instCdBase;
                                param.aprvlCndNbr = that.$el.find('[data-form-param="aprvlCndNbr"]').val();


                                // 그리드부 재조회
                                that.trigger('loadData', param);


                                //상세부에 조회된 분개규칙일련번호전달
                                that.trigger('loadAprvlCndNbr', param);
                            }
                        }
                    } // end of success: function.....
                }); // end of bxProxy.post....
            } // end of select function


            /* ======================================================================== */
            /*    Click save btn                                                      */
            /* ======================================================================== */
            , savePWF508Base: function (e) {
                var that = this;
                var sParam = {};
                var instCdBase = "";


                if (commonInfo.getInstInfo().instCd) {
                	instCdBase = commonInfo.getInstInfo().instCd;
                } else {
                	instCdBase = $.sessionStorage('headerInstCd');
                }


                // 입력항목 set
                sParam.instCd = instCdBase;
                sParam.aprvlCndNbr = that.$el.find('[data-form-param="aprvlCndNbr"]').val();
                sParam.srvcCd = that.$el.find('[data-form-param="srvcCd"]').val();
                sParam.aprvlPtrnDscd = that.$el.find('[data-form-param="aprvlPtrnDscd"]').val();
                sParam.stsCd = that.$el.find('[data-form-param="stsCd"]').val();
                sParam.aprvlTmpltId = that.$el.find('[data-form-param="aprvlTmpltId"]').val();
                sParam.aprvlRsnCd = that.$el.find('[data-form-param="aprvlRsnCd"]').val();
                sParam.amtCndYn = that.$el.find('[data-form-param="amtCndYn"]').val();


                sParam.amtTpCd = that.$el.find('[data-form-param="amtTpCd"]').val();
                sParam.amtCndMinVal = that.$el.find('[data-form-param="amtCndMinVal"]').val();
                sParam.amtCndMaxVal = that.$el.find('[data-form-param="amtCndMaxVal"]').val();
                sParam.crncyCdCndYn = that.$el.find('[data-form-param="crncyCdCndYn"]').val();
                sParam.crncyCd = that.$el.find('[data-form-param="crncyCd"]').val();
                sParam.txHmsCndYn = that.$el.find('[data-form-param="txHmsCndYn"]').val();
                sParam.txStartHms = that.$el.find('[data-form-param="txStartHms"]').val();
                sParam.txEndHms = that.$el.find('[data-form-param="txEndHms"]').val();
                sParam.txBrnchDscdCndYn = that.$el.find('[data-form-param="txBrnchDscdCndYn"]').val();
                sParam.txBrnchDscd = that.$el.find('[data-form-param="txBrnchDscd"]').val();
                sParam.txBrnchCndYn = that.$el.find('[data-form-param="txBrnchCndYn"]').val();
                sParam.txBrnchCd = that.$el.find('[data-form-param="txBrnchCd"]').val();




                sParam.pdCndYn = that.$el.find('[data-form-param="pdCndYn"]').val();
                sParam.bizDscd = that.$el.find('[data-form-param="bizDscd"]').val();
                sParam.pdTpCd = that.$el.find('[data-form-param="pdTpCd"]').val();
                sParam.pdTmpltCd = that.$el.find('[data-form-param="pdTmpltCd"]').val();
                sParam.pdCd = that.$el.find('[data-form-param="pdCd"]').val();
                sParam.pdNm = that.$el.find('[data-form-param="pdNm"]').val();


                // 날짜 데이터는 형식을 변환해야 함 yyyy-mm-dd ==> yyyymmdd
                sParam.aplyStartDt = that.subViews['aplyStartDt'].getValue();
                sParam.aplyEndDt = that.subViews['aplyEndDt'].getValue();


                if (that.$el.find('[data-form-param="amtCndYn"]').is(':checked')) {
                    if (sParam.amtTpCd == undefined || sParam.amtTpCd == '') {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#amtTpCd") + "]");
                        that.$el.find('[data-form-param="amtTpCd"]').focus();


                        return;
                    }


                    if (sParam.amtCndMinVal == undefined || sParam.amtCndMinVal == '' || !jQuery.isNumeric(sParam.amtCndMinVal)) {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#amtCndMinVal") + "]");
                        that.$el.find('[data-form-param="amtCndMinVal"]').focus();


                        return;
                    }


                    if (sParam.amtCndMaxVal == undefined || sParam.amtCndMaxVal == '' || !jQuery.isNumeric(sParam.amtCndMaxVal)) {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#amtCndMaxVal") + "]");
                        that.$el.find('[data-form-param="amtCndMaxVal"]').focus();


                        return;
                    }
                }


                if (that.$el.find('[data-form-param="crncyCdCndYn"]').is(':checked')) {
                    if (sParam.crncyCd == undefined || sParam.crncyCd == '') {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#crncyCd") + "]");
                        that.$el.find('[data-form-param="crncyCd"]').focus();


                        return;
                    }
                }


                if (that.$el.find('[data-form-param="txHmsCndYn"]').is(':checked')) {
                    if (sParam.txStartHms == undefined || sParam.txStartHms == '') {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#txStartHms") + "]");
                        that.$el.find('[data-form-param="txStartHms"]').focus();


                        return;
                    }


                    if (sParam.txEndHms == undefined || sParam.txEndHms == '') {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#txEndHms") + "]");
                        that.$el.find('[data-form-param="txEndHms"]').focus();


                        return;
                    }
                }


                if (that.$el.find('[data-form-param="txBrnchDscdCndYn"]').is(':checked')) {
                    if (sParam.txBrnchDscd == undefined || sParam.txBrnchDscd == '') {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#txBrnchDscd") + "]");
                        that.$el.find('[data-form-param="txBrnchDscd"]').focus();


                        return;
                    }
                }


                if (that.$el.find('[data-form-param="txBrnchCndYn"]').is(':checked')) {
                    if (sParam.txBrnchCd == undefined || sParam.txBrnchCd == '') {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#txBrnchCd") + "]");
                        that.$el.find('[data-form-param="txBrnchCd"]').focus();


                        return;
                    }
                }


                if (that.$el.find('[data-form-param="pdCndYn"]').is(':checked')) {
                    if (sParam.bizDscd == undefined || sParam.bizDscd == '') {
                        alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#bizDscd") + "]");
                        that.$el.find('[data-form-param="bizDscd"]').focus();


                        return;
                    }
                }


                if (initFlag) { // 등록
                    var linkData = {"header": fn_getHeader("PWF4028101"), "AprvlCndMgmtSvcAprvlCondBsicInfoIO": sParam};
                }
                else { // 수정
                    var linkData = {"header": fn_getHeader("PWF4028201"), "AprvlCndMgmtSvcAprvlCondBsicInfoIO": sParam};
                }


                //ajax 호출
                bxProxy.post(sUrl, JSON.stringify(linkData), {
                    success: function (responseData) {
                        // 에러여부 확인. 에러시 메시지 띄워주고 정상시 재조회 호출
                        if (fn_commonChekResult(responseData)) {
                            // 정상처리 메시지 출력
                            alertMessage.info(bxMsg('cbb_items.SCRNITM#success'));


                            if (responseData.AprvlCndMgmtSvcAprvlCondBsicInfoIO.aprvlCndNbr != null) {


                                that.$el.find('[data-form-param="aprvlCndNbr"]').val(responseData.AprvlCndMgmtSvcAprvlCondBsicInfoIO.aprvlCndNbr);


                                // 기본부 재조회
                                that.selectPWF508Base();


                                // 첫번째 tab의 조회기능을 트리거하여 그리드도 처리함
                                var param = {};
                                param.instCd = instCdBase;
                                param.aprvlCndNbr = sParam.aprvlCndNbr;


                                if (param.aprvlCndNbr == '') {
                                    param.aprvlCndNbr = responseData.AprvlCndMgmtSvcAprvlCondBsicInfoIO.aprvlCndNbr;
                                }


                                // 그리드부 재조회
                                that.trigger('loadData', param);


                                //상세부에 조회된 번호전달
                                that.trigger('loadAprvlCndNbr', param);
                            }


                        }
                    } // end of success: function
                }); // end of bxProxy.post.....
            } // end of create function


            /* ======================================================================== */
            /*    Click delete btn                                                      */
            /* ======================================================================== */
            , deletePWF508Base: function (e) {
                var that = this;
                var sParam = {};
                var instCdBase = "";


                if (commonInfo.getInstInfo().instCd) {
                	instCdBase = commonInfo.getInstInfo().instCd;
                } else {
                	instCdBase = $.sessionStorage('headerInstCd');
                }
                // 입력항목 set
                sParam.instCd = instCdBase;
                sParam.aprvlCndNbr = that.$el.find('[data-form-param="aprvlCndNbr"]').val();


                if (fn_isEmpty(sParam.aprvlCndNbr)) {
                    alertMessage.error(bxMsg('cbb_err_msg.UICME0004') + " [" + bxMsg("cbb_items.AT#aprvlCndNbr") + "]");
                    that.$el.find('[data-form-param="aprvlCndNbr"]').focus();
                    return;
                }


                var linkData = {"header": fn_getHeader("PWF4028301"), "AprvlCndMgmtSvcAprvlCondBsicInfoIO": sParam};


                //ajax 호출
                bxProxy.post(sUrl, JSON.stringify(linkData), {
                    success: function (responseData) {
                        if (fn_commonChekResult(responseData)) {
                            // 정상처리 메시지 출력
                            alertMessage.info(bxMsg('cbb_items.SCRNITM#success'));
                            that.resetPWF508Base();
                        }
                    } // end of success: function
                }); // end of bxProxy.post.....
            } // end of delete function


            /* ======================================================================== */
            /*  상품 대분류코드 변경 event 처리 */
            /* ======================================================================== */
            , changeBizDscd: function () {
                var that = this;
                var sParam = {};
                var selectStyle = {};
                var param = {};
                // 상품대분류코드
                var bizDscd = that.$el.find('[data-form-param="bizDscd"]').val();


                //상품중분류코드 재조회
                param.bizDscd = bizDscd;
                that.selectPdTpCd(param);
            }


            /* ======================================================================== */
            /*  상품 중분류코드 변경 event 처리 */
            /* ======================================================================== */
            , changePdTpCd: function () {
                var that = this;
                var sParam = {};
                var selectStyle = {};
                var param = {};
                // 상품중분류코드
                var pdTpCd = that.$el.find('[data-form-param="pdTpCd"]').val();


                // 상품대분류코드+ 상품중분류코드
                param.bizDscd = that.$el.find('[data-form-param="bizDscd"]').val();
                param.pdTpCd = pdTpCd;


                //상품템플릿코드 재조회
                that.selectPdTmpltCd(param);
            }
            /* ======================================================================== */
            /*	  상품템플릿코드 변경 event 처리 */
            /* ======================================================================== */
            , changePdTmpltCd: function () {
                var that = this;
                var sParam = {};
                var selectStyle = {};
                var param = {};
                // 상품템플릿코드
                var pdTmpltCd = that.$el.find('[data-form-param="pdTmpltCd"]').val();




                // 상품대분류코드+ 상품중분류코드
                param.bizDscd = that.$el.find('[data-form-param="bizDscd"]').val();
                param.pdTpCd = that.$el.find('[data-form-param="pdTpCd"]').val();
                param.pdTmpltCd = pdTmpltCd;


                //상품템플릿코드 재조회
                that.selectPdCd(param);
            }


            /* ======================================================================== */
            /*  상품 중분류코드 조회 */
            /* ======================================================================== */
            , selectPdTpCd: function (param) {
                var that = this;
                var sParam = {};
                var selectStyle = {};
                sParam = {}; //데이터 초기화
                selectStyle = {}; //스타일 초기화


                if (param.bizDscd == "") {
                    //상품중분류코드 초기화
                    that.initPdTpCd();
                }
                else {
                    //combobox 정보 셋팅
                    sParam.className = "PWF508-pdTpCd-wrap";
                    sParam.targetId = "pdTpCd";
                    sParam.nullYn = "Y";
                    //inData 정보 셋팅
                    sParam.instCd = commonInfo.getInstInfo().instCd;
                    sParam.bizDscd = param.bizDscd;
                    sParam.pdTpCd = "";
                    //상품중분류코드 콤보데이터 load
                    fn_getPdCodeList(sParam, that, selectStyle);
                }


                //상품템플릿 초기화
                that.initPdTmpltCd();
            }
            /* ======================================================================== */
            /*    상품탬플릿코드 조회                                */
            /* ======================================================================== */
            , selectPdTmpltCd: function (param) {
                var that = this;
                var sParam = {};
                var selectStyle = {};
                sParam = {}; //데이터 초기화
                selectStyle = {}; //스타일 초기화


                if (param.pdTpCd == "") {
                    //상품템플릿 초기화
                    that.initPdTmpltCd();
                }
                else {
                    //combobox 정보 셋팅
                    sParam.className = "PWF508-pdTmpltCd-wrap";
                    sParam.targetId = "pdTmpltCd";
                    sParam.nullYn = "Y";
                    //inData 정보 셋팅
                    sParam.instCd = commonInfo.getInstInfo().instCd;
                    sParam.bizDscd = param.bizDscd;
                    sParam.pdTpCd = param.pdTpCd;
                    // 상품탬플릿코드 콤보데이터 load
                    fn_getPdCodeList(sParam, that, selectStyle);
                }


                that.initPdCd();
            }
            /* ======================================================================== */
            /*    상품코드 조회                                */
            /* ======================================================================== */
            , selectPdCd: function (param) {
                var that = this;
                var sParam = {};
                var selectStyle = {};
                sParam = {}; //데이터 초기화
                selectStyle = {}; //스타일 초기화


                if (param.pdCd == "") {
                    //상품템플릿 초기화
                    that.initPdCd();
                }
                else {
                    //combobox 정보 셋팅
                    sParam.className = "CAPWF508-pdCd-wrap";
                    sParam.targetId = "pdCd";
                    sParam.nullYn = "Y";
                    //inData 정보 셋팅
                    sParam.instCd = $.sessionStorage('headerInstCd');
                    sParam.bizDscd = param.bizDscd;
                    sParam.pdTpCd = param.pdTpCd;
                    sParam.pdTmpltCd = param.pdTmpltCd;
                    // 상품탬플릿코드 콤보데이터 load
                    fn_getPdCodeList(sParam, that, selectStyle);
                }
            }




            /* ======================================================================== */
            /*    상품중분류코드 초기화                                */
            /* ======================================================================== */
            , initPdTpCd: function () {
                var sParam = {};
                var selectStyle = {};
                // 상품템플릿코드 리셋
                selectStyle = {};//'width':100};


                sParam.className = "PWF508-pdTpCd-wrap";
                sParam.targetId = "pdTpCd";
                //상품중분류코드
                fn_getEmptyCombo(sParam, this, selectStyle);
            }


            /* ======================================================================== */
            /*    상품템플릿코드 초기화                                */
            /* ======================================================================== */
            , initPdTmpltCd: function () {
                var sParam = {};
                var selectStyle = {};
                // 상품템플릿코드 리셋
                selectStyle = {};//'width':100};


                sParam.className = "PWF508-pdTmpltCd-wrap";
                sParam.targetId = "pdTmpltCd";
                //상품중분류코드
                fn_getEmptyCombo(sParam, this, selectStyle);
            }


            /* ======================================================================== */
            /*    상품코드 초기화                                */
            /* ======================================================================== */
            , initPdCd: function () {
                var sParam = {};
                var selectStyle = {};
                // 상품템플릿코드 리셋
                selectStyle = {};//'width':100};


                sParam.className = "PWF508-pdCd-wrap";
                sParam.targetId = "pdCd";
                //상품중분류코드
                fn_getEmptyCombo(sParam, this, selectStyle);
            }


            /* ======================================================================== */
            /*  데이터 피커 로드 컴포넌트 데이터 피커를 사용
             /*  ('libs/bx/bx-ui/component/date-picker/_date-picker.js' 참조)
             /* ======================================================================== */
            , loadDatePicker: function () {


                this.subViews['aplyStartDt'] && this.subViews['aplyStartDt'].remove();
                // 적용시작년월일 데이터 피커 생성
                this.subViews['aplyStartDt'] = new DatePicker({
                    inputAttrs: {'data-form-param': 'aplyStartDt'},
                    setTime: false
                });
                // 적용시작년월일데이터 피커 렌더
                this.$el.find('.PWF508-aplyStartDt-wrap').html(this.subViews['aplyStartDt'].render());


                this.subViews['aplyEndDt'] && this.subViews['aplyEndDt'].remove();
                // 적용종료년월일 데이터 피커 생성
                this.subViews['aplyEndDt'] = new DatePicker({
                    inputAttrs: {'data-form-param': 'aplyEndDt'},
                    setTime: false
                });
                // 적용종료년월일데이터 피커 렌더
                this.$el.find('.PWF508-aplyEndDt-wrap').html(this.subViews['aplyEndDt'].render());


            }


            /* ======================================================================== */
            /*  서비스코드조회 팝업          */
            /* ======================================================================== */
            , fn_popupSrvcCd: function () {


                var that = this;


                var popupSrvcCd = new PopupSrvcCd(); // 팝업생성
                popupSrvcCd.render();


                popupSrvcCd.on('popUpSetData', function (param) {
                    that.$el.find('[data-form-param="srvcCd"]').val(param.srvcCd); //서비스코드
                    that.$el.find('[data-form-param="srvcNm"]').val(param.srvcNm); //서비스코드
                });
            }


            /* ======================================================================== */
            /*  결재탬플릿식별자 팝업          */
            /* ======================================================================== */
            , fn_popupAprvlId: function () {


                var that = this;
                var sParam = {};


                var instInfo = commonInfo.getInstInfo();
                sParam.instCd = instInfo.instCd;


                var popupAprvlTmplt = new PopupAprvlTmplt(sParam); // 팝업생성


                popupAprvlTmplt.render();


                popupAprvlTmplt.on('popUpSetData', function (param) {
                    that.$el.find('[data-form-param="aprvlTmpltId"]').val(param.aprvlTmpltId); //결재탬플릿식별자
                    that.$el.find('[data-form-param="aprvlTmpltNm"]').val(param.aprvlTmpltNm); //결재탬플릿식별자
                });
            }


            /* ======================================================================== */
            /*  부점코드조회 팝업          */
            /* ======================================================================== */
            , fn_popupBrnchCd: function () {


                var that = this;


                var popupBrnchCd = new PopupBrnchCd(); // 팝업생성
                popupBrnchCd.render();


                popupBrnchCd.on('popUpSetData', function (param) {
                    that.$el.find('[data-form-param="txBrnchCd"]').val(param.brnchCd); //부점코드
                });
            }
            /* ======================================================================== */
            /*  상품코드 조회및 셋팅          */
            /* ======================================================================== */
            , fn_PdList: function (sParam, that, selectStyle) {


                var param = {};


                param.bizDscd = sParam.bizDscd;
                param.pdTpCd = sParam.pdTpCd;
                (sParam.tpTmpltCd) && (param.tpTmpltCd = sParam.tpTmpltCd);


                var linkData = {"header": fn_getHeader("SPD0010401"), "PdTxSrvcMgmtSvc01In": param};


                //ajax 호출
                bxProxy.post(sUrl, JSON.stringify(linkData), {
                    success: function (data) {


                        if (fn_commonChekResult(data)) {


                            var sectionArea = $(document.createElement('section'));
                            sectionArea.addClass("bx-combo-box-wrap");
                            sParam.className = "." + sParam.className;
                            that.$el.find(sParam.className).html("");


                            var selectArea = $(document.createElement('select'));
                            $(selectArea).addClass("bx-combo-box bx-form-item bx-compoenent-small");
                            selectStyle && $(selectArea).css(selectStyle);
                            $(selectArea).attr("data-form-param", sParam.targetId);


                            if (sParam.nullYn == "Y") {
                                var option = $(document.createElement('option')).val("").text(" ");
                                $(selectArea).append(option);
                            }


                            $(data.PdTxSrvcMgmtSvcOut.tbl).each(function (idx, item) {
                                var optionText = item.pdNm;
                                var option = $(document.createElement('option')).val(item.pdCd).text(optionText);


                                $(selectArea).append(option);
                            });
                            $(sectionArea).html(selectArea);


                            that.$el.find(sParam.className).html(sectionArea);




                            //상품코드조회후 셋팅
                            that.$el.find('[data-form-param="bizDscd"]').val(bizDscd);       //상품대분류코드
                            that.$el.find('[data-form-param="pdTpCd"]').val(pdTpCd);       //상품중분류코드
                            that.$el.find('[data-form-param="pdTmpltCd"]').val(pdTmpltCd);       //상품템플릿코드
                            that.$el.find('[data-form-param="pdCd"]').val(pdCd);       //상품코드
                        }
                    }//end of success
                });//end of bxProxy
            }//end of fn_PdList
        }); // end of Backbone.View.extend


        return PWF508BaseView;
    } // end of define function
); // end of define
