// Generated by Bankware Global CBB Solution Center on 2015-02-04-00:32:02


define(
    [
        'bx/common/config'
        , 'bx-component/message/message-alert'
        , 'bx-component/message/message-confirm'
        , 'bx-component/ext-grid/_ext-grid'
        , 'text!app/views/page/PWF/011/PWF011-list-tpl.html'
        , 'app/views/page/popup/CAPCM/popup-message'
        , 'bx/common/common-message'
    ],
    function (config
        , alertMessage
        , confirmMessage
        , ExtGrid
        , tpl
        , PopupMessage) {


        // 전역변수 선언
        var chkAddCol = false;
        var wflowId;


        var comboStore1 = {}; // 프로세스유형
        var comboStore2 = {}; // 적용상태구분
        var comboStore3 = {}; // 업무영역구분


        var PWF011TabView = Backbone.View.extend({


            // 태그이름 설정
            tagName: 'section',


            // 클래스 이름 설정
            className: 'PWF011-list-page',


            // 템플릿 설정
            templates: {
                'tpl': tpl
            }


            // 이벤트 설정
            , events: {
                'click.bx-tab-container .bx-tab-menu-item': 'changeTab'
            }


            // 탭에 따라 호출될 메소드 지정
            , subPageRenderMap: {
                'PWF011-single-tab': 'selSingle'
            }


            , initialize: function (initData) {
                var that = this;


                $.extend(that, initData);


                // 페이지 템플릿 설정
                that.$el.html(that.tpl());


                // 콤보조회 서비스호출 준비
                var sParam = {};


                // 프로세스유형
                sParam = {};
                sParam.cdNbr = "11905";
                var linkData1 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                // 적용상태구분
                sParam = {};
                sParam.cdNbr = "11902";
                var linkData2 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                // 업무영역구분
                sParam = {};
                sParam.cdNbr = "11603";
                var linkData3 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                /* ========================================================== */
                bxProxy.all([
                    /* ========================================================== */
                    // 프로세스유형 콤보코드 로딩
                    {
                        url: sUrl, param: JSON.stringify(linkData1), success: function (responseData) {
                        if (fn_commonChekResult(responseData)) {
                            comboStore1 = new Ext.data.Store({
                                fields: ['cd', 'cdNm'],
                                data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tbl
                            });
                        }
                    }
                    }
                    // 적용상태구분 콤보코드 로딩
                    , {
                        url: sUrl, param: JSON.stringify(linkData2), success: function (responseData) {
                            if (fn_commonChekResult(responseData)) {
                                comboStore2 = new Ext.data.Store({
                                    fields: ['cd', 'cdNm'],
                                    data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tbl
                                });
                            }
                        }
                    }
                    // 업무영역구분 콤보코드 로딩
                    , {
                        url: sUrl, param: JSON.stringify(linkData3), success: function (responseData) {
                            if (fn_commonChekResult(responseData)) {
                                comboStore3 = new Ext.data.Store({
                                    fields: ['cd', 'cdNm'],
                                    data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tbl
                                });
                            }
                        }
                    }
                ], {
                    success: function () {
                        /* ------------------------------------------------------------ */
                        that.PWF011SingleGrid = new ExtGrid({
                            /* ------------------------------------------------------------ */
                            // 단일탭 그리드 컬럼 정의
                            fields: ['No', 'wflowId', 'wflowNm', 'wflowTpCd', 'wflowAplyStsCd', 'bizCmpntCd', 'aplyStartDt', 'aplyEndDt', 'rmk']
                            , id: 'PWF011SingleGrid'
                            , columns: [
                                {
                                    text: "No"
                                    , dataIndex: 'rowIndex'
                                    , sortable: false
                                    , width: 30
                                    , style: 'text-align:center', align: 'right'
                                    , renderer: function (value, metaData, record, rowIndex, colIndex, store) {
                                    return rowIndex + 1;
                                }
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#wflowId'),
                                    width: 200,
                                    dataIndex: 'wflowId',
                                    style: 'text-align:center',
                                    align: 'left'
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#wflowNm'),
                                    width: 250,
                                    dataIndex: 'wflowNm',
                                    style: 'text-align:center',
                                    align: 'left'
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#wflowTpCd'),
                                    width: 90,
                                    dataIndex: 'wflowTpCd',
                                    style: 'text-align:center',
                                    align: 'center',
                                    hidden: true
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore1
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore1.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore1.getAt(index).data;
                                            return rs.cdNm;
                                        }
                                    } // end of render
                                } // end of 프로세스유형
                                , {
                                    text: bxMsg('cbb_items.AT#aplyStsDstnctn'),
                                    width: 80,
                                    dataIndex: 'wflowAplyStsCd',
                                    style: 'text-align:center',
                                    align: 'center',
                                    hidden: true
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore2
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore2.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore2.getAt(index).data;
                                            return rs.cdNm;
                                        }
                                    } // end of render
                                } // end of 적용상태구분
                                , {
                                    text: bxMsg('cbb_items.AT#bizCmpntCd'),
                                    width: 150,
                                    dataIndex: 'bizCmpntCd',
                                    style: 'text-align:center',
                                    align: 'left'
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore3
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore3.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore3.getAt(index).data;
                                            return rs.cdNm;
                                        }
                                    } // end of render
                                } // end of 업무영역구분
                                , {
                                    text: bxMsg('cbb_items.AT#aplyStartDt'),
                                    width: 90,
                                    dataIndex: 'aplyStartDt',
                                    style: 'text-align:center',
                                    align: 'center',
                                    hidden: true
                                    ,
                                    renderer: function (val) {
                                        if (val == null) {
                                            return;
                                        } else {
                                            return XDate(val).toString('yyyy-MM-dd');
                                        }
                                    }
                                    ,
                                    editor: new Ext.form.DateField({
                                        allowBlank: false
                                        , xtype: 'datefield'
                                        , format: 'Y-m-d'
                                        , minValue: new Date()
                                    })
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#aplyEndDt'),
                                    width: 90,
                                    dataIndex: 'aplyEndDt',
                                    style: 'test-align:center',
                                    align: 'center',
                                    hidden: true
                                    ,
                                    renderer: function (val) {
                                        if (val == null) {
                                            return;
                                        } else {
                                            return XDate(val).toString('yyyy-MM-dd');
                                        }
                                    }
                                    ,
                                    editor: new Ext.form.DateField({
                                        allowBlank: false
                                        , xtype: 'datefield'
                                        , format: 'Y-m-d'
                                        , minValue: new Date()
                                    })
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#rmk'),
                                    width: 350,
                                    dataIndex: 'rmk',
                                    style: 'text-align:center',
                                    align: 'left'
                                }
                            ]


                            // 컴포넌트 그리드('libs/bx/bx-ui/component/ext-grid/_ext-grid.js' 참조) 에서 정의한 것 외에 추가할 경우 gridConfig에 추가
                            , gridConfig: {
                                // 셀 에디팅 플러그인
                                // 2번 클릭시, 에디팅할 수 있도록 처리
//                             plugins: [
//                                 Ext.create('Ext.grid.plugin.CellEditing', {
//                                     clicksToEdit : 2
//                                 }) // end of Ext.create
//                             ] // end of plugins
                            } // end of gridConfig
                            , listeners: {
                                click: {
                                    element: 'body',
                                    fn: function () {
                                        console.log('click event caught.');
                                        //클릭시 이벤트 발생
                                        that.selectReocrd();
                                    }
                                }
                            }


                        });
                        // 단일탭 그리드 렌더
                        that.createGrid("single");


                    } // end of success:.function
                }); // end of bxProxy.all
            } // end of initialize:


            // 첫번째 탭 활성화 설정
            , render: function () {
                this.currentSubTab = 'PWF011-single-tab';
                return this.$el;
            }


            // 그리드 생성
            , createGrid: function (target) {
                if (target == "single") {
                    this.$el.find(".PWF011-single-grid").html(this.PWF011SingleGrid.render({'height': CgridHeight}));
                }
            } // end of createGrid


            // 탭 변경 이벤트 처리
            , changeTab: function (e) {
                var $clickedTab = $(e.currentTarget),
                    pageLink = $clickedTab.attr('data-link'),
                    $tabs = $clickedTab.siblings('.bx-tab-menu-item'),
                    $pages = $clickedTab.parents('.bx-tab-menu').next().find('.bx-tab-page');


                // 활성화 되어있는 탭과 페이지 비활성화 처리
                $tabs.filter('.is-active').removeClass('is-active');
                $pages.filter('.is-active').removeClass('is-active');


                // 클릭된 탭과 페이지 활성화 처리
                $clickedTab.addClass('is-active');
                $pages.filter('[data-link="' + pageLink + '"]').addClass('is-active');


                // 현재 활성화 탭 설정
                this.currentSubTab = pageLink;
                $pages.filter('[data-link="' + pageLink + '"]').show();




                // 탭에 연결된 메소드 호출
                this.renderSubPage();
            }


            // 텝에 연결된 매소드 호출
            , renderSubPage: function (param) {
                var subPageRenderName = this.subPageRenderMap[this.currentSubTab];


                // 기본부에서 넘어온 파라미터를 현재창의 전역변수에 넣는다
                this.settedParam = param;


                (typeof this[subPageRenderName] === 'function') && this[subPageRenderName]();
            }


            // 그리드의 날짜컬럼의 포맷변경 yyyymmdd ==> yyyy-mm-dd
            , setGridDate: function (val) {
                var now = new Date(val);
                var returnVal = val;


                if (isNaN(now.getFullYear())) {
                    if (val.length == 8) {
                        val = val.substring(0, 4) + "-" + val.substring(4, 6) + "-" + val.substring(6, 8);
                    }
                    returnVal = val;
                }
                else {
                    var year = now.getFullYear();
                    var month = now.getMonth() + 1;
                    var date = now.getDate();


                    if ((month + "").length < 2) {
                        month = "0" + month;   //달의 숫자가 1자리면 앞에 0을 붙임.
                    }
                    if ((date + "").length < 2) {
                        date = "0" + date;
                    }
                    returnVal = year + "-" + Month + "-" + date;
                }
                return returnVal;
            }


            // 그리드의 날짜컬럼의 포맷 변경 yyyy-mm-dd ==> yyyymmdd
            , getGridDate: function (val) {
                var now = new Date(val);
                var returnVal;
                if (isNaN(now.getFullYear())) {
                    returnVal = val;
                }
                else {
                    var year = now.getFullYear();
                    var month = now.getMonth() + 1;
                    var date = now.getDate();


                    if ((month + "").length < 2) {
                        month = "0" + month;   //달의 숫자가 1자리면 앞에 0을 붙임.
                    }
                    if ((date + "").length < 2) {
                        date = "0" + date;
                    }


                    returnVal = year + "" + month + "" + date;
                }
                return returnVal;
            }


            //그리드 클릭시 이벤트 처리
            , selectReocrd: function () {
                var that = this;
                var selectedRecord = that.PWF011SingleGrid.grid.getSelectionModel().selected.items[0];


                if (selectedRecord != null && selectedRecord.data != null) {
                    wflowId = selectedRecord.data.wflowId;
                }


                that.insertIframe();


                /*
                 if(!selectedRecord){
                 return;
                 } else {
                 that.$el.trigger({
                 type: 'open-conts-page',
                 pageHandler: 'PWF010',
                 pageDPName: bxMsg('cbb_items.SCRN#PWF010'),
                 pageInitialize: true,


                 pageRenderInfo: {
                 wflowId: selectedRecord.data.wflowId,
                 wflowNm: selectedRecord.data.wflowNm
                 }
                 });
                 }
                 */
            }


            /* ============================================================== */
            /*  Single 조회         */
            /* ============================================================== */
            , selSingle: function () {
                chkAddcol = false;
                var that = this;
                var sParam = {};
                var param = this.settedParam;


                // 입력 Key값 set
                sParam.instCd = param.instCd;
                sParam.wflowId = param.wflowId;  // 프로세스식별자
                // sParam.wflowNm = param.wflowNm;  // 프로세스명
                sParam.wflowTpCd = param.wflowTpCd;  // 프로세스유형
                sParam.wflowAplyStsCd = param.wflowAplyStsCd;  // 적용상태구분
                sParam.bizCmpntCd = param.bizCmpntCd;  // 업무영역구분


                var linkData = {"header": fn_getHeader("PWF0118401"), "WflowMgmtSvcGetWflowListInqryIn": sParam};


                // ajax호출
                bxProxy.post(sUrl, JSON.stringify(linkData), {
                    enableLoading: true,
                    success: function (responseData) {
                        if (fn_commonChekResult(responseData)) {
                            var tbList = responseData.WflowMgmtSvcGetWflowListInqryOut.wflowList;
                            if (tbList != null || tbList.length > 0) {
                                that.PWF011SingleGrid.setData(tbList);
                            }
                            else {
                                that.PWF011SingleGrid.resetData();
                            }
                        }
                    }   // end of suucess: fucntion
                });     // end of bxProxy
            } // end of 조회


            /* ============================================================== */
            /*  insertIframe         */
            /* ============================================================== */
            , insertIframe: function () {
                chkAddcol = false;
                var that = this;


                that.$el.find('#scaled-frame-processInstance').attr('src', baseUrl + '/activiti-explorer/diagram-viewer/index.html?processDefinitionId=' + wflowId);
            } // end of 조회


        }); // end of PWF011TabView = Backbone.View.extend


        return PWF011TabView;
    }  // end of main function
);
