// Generated by Bankware Global CBB Solution Center on 2015-02-04 오전 1:07:03


define(
    [
        'bx/common/config'
        , 'text!app/views/page/CAPSV/003/_CAPSV003.html'
        , 'bx-component/ext-grid/_ext-grid'
        , 'bx-component/date-picker/_date-picker'
        , 'bx/common/common-info'
        , 'app/views/page/popup/CAPSV/popup-service'
    ]
    , function (config
            , tpl
            , ExtGrid
            , DatePicker
            , commonInfo
            , PopupSrvcCd
            ) {
        var comboStore1 = {}; // 제한유형
        var comboStore2 = {}; // 채널코드
        var comboStore3 = {}; // 상품대분류


            /**
             * Backbone
             */
            var CAPSV003View = Backbone.View.extend({
                    // 태그이름 설정
                    tagName: 'section'
                    // 클래스이름 설정
                    , className: 'bx-container CAPSV003-page'
                    // 탬플릿 설정
                    , templates: {
                        'tpl': tpl
                    }
                    // 이벤트 설정
                    , events: {
                         'change .CAPSV003-base-bizDscd-wrap': 'changeBizDscd'
                        , 'change .CAPSV003-base-pdTpCd-wrap': 'changePdMClcd'
                        , 'change .CAPSV003-base-pdTmpltCd-wrap': 'changePdTmpltCd'
                        , 'change .CAPSV003-detail-bizDscd-wrap': 'changeBizDscd2'
                        , 'change .CAPSV003-detail-pdTpCd-wrap': 'changePdMClcd2'
                        , 'change .CAPSV003-detail-pdTmpltCd-wrap': 'changePdTmpltCd2'
                        , 'click #btn-srvcCd-search':'popupSrvcCd'
                        , 'click #btn-srvcCd-search2':'popupSrvcCd2'
                        , 'click #btn-base-reset': 'resetPSV003Detl'
                        , 'click #btn-detail-refresh': 'resetPSV003Detl2'
                        , 'click #btn-detail-save': 'savePSV003Detl'
                        , 'click #btn-detail-delete': 'deletePSV003Detl'
                        , 'click #btn-search-condition-inquire': 'select'
                    }






                    /**
                     * 서비스입력항목 조회
                     */
                    ,select : function(that) {
                        var param = {};
                        var that = this;


                        // 조회 key값 set
                        param.instCd = $.sessionStorage('headerInstCd');
                        param.srvcRstrctnCd = this.$el.find('[data-form-param="srvcRstrctnCd"]').val(); // 제한코드
                        param.srvcCd = this.$el.find('[data-form-param="srvcCd"]').val(); // 서비스코드
                        param.chnlCd = this.$el.find('[data-form-param="chnlCd"]').val(); // 채널코드
                        param.bizDscd = this.$el.find('[data-form-param="bizDscd"]').val(); // 상품대분류
                        param.pdTpCd = this.$el.find('[data-form-param="pdTpCd"]').val(); // 상품중분류
                        param.pdTmpltCd = this.$el.find('[data-form-param="pdTmpltCd"]').val(); // 상품템플릿
                        param.pdCd = this.$el.find('[data-form-param="pdCd"]').val(); // 상품코드


                        var linkData = {"header": fn_getHeader("CAPSV0038408"), "CaSrvcRstrctnDtlMgmtSvcGetSrvcRstrctnIn": param};


                        // ajax호출
                        bxProxy.post(sUrl, JSON.stringify(linkData), {
                            enableLoading: true,
                            success: function (responseData) {
                                if (fn_commonChekResult(responseData)) {
                                	// 서비스 입력항목
                                	var data = responseData.CaSrvcRstrctnDtlMgmtSvcGetSrvcRstrctnOut;




                                	// 서비스 입력항목
                                   // that.resetServiceInputItem();
                                    if (data.tblNm != null || data.tblNm.length > 0) {
                                    	that.CAPSV003Grid.setData(data.tblNm);


                                    	// 삭제 로우 초기화
                                    	that.deleteList = [];
                                    }
                                }
                            }   // end of suucess: fucntion
                        });     // end of bxProxy
                    }
                    ,setTimeInput: function () {
                        this.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').mask("99:99:99", {placeholder:"--:--:--"});
                        this.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').mask("99:99:99", {placeholder:"--:--:--"});
                    }
                    /**
                     *  서비스코드조회 팝업          
                     */
                    , popupSrvcCd: function () {


                        var that = this;
                        var sParam = {};
                      //  sParam.cmpntCd=that.$el.find('.CAPMT001-base-table [data-form-param="cmpntCd"]').val();
                        var popupSrvcCd = new PopupSrvcCd(sParam); // 팝업생성
                        popupSrvcCd.render();                   
                        popupSrvcCd.on('popUpSetData', function (param) {
                            that.$el.find('#CAPSV003-detail-table [data-form-param="srvcCd"]').val(param.srvcCd); //서비스코드
//                            that.$el.find('[data-form-param="srvcNm"]').val(param.srvcNm); 
                        });
                    }
                    , popupSrvcCd2: function () {


                        var that = this;
                        var sParam = {};
                      //  sParam.cmpntCd=that.$el.find('.CAPMT001-base-table [data-form-param="cmpntCd"]').val();
                        var popupSrvcCd = new PopupSrvcCd(sParam); // 팝업생성
                        popupSrvcCd.render();                   
                        popupSrvcCd.on('popUpSetData', function (param) {
                            that.$el.find('#CAPSV003-base-table [data-form-param="srvcCd"]').val(param.srvcCd); //서비스코드
//                            that.$el.find('[data-form-param="srvcNm"]').val(param.srvcNm); 
                        });
                    }




    //
    //
    //
                    , initialize: function (initData) {                    	
                        var that = this;
                        var sParam = {};
                        that.initFlag = true;


                        $.extend(that, initData);
                        that.$el.html(that.tpl());


                        that.initData = initData;


                        // 제한유형
                        sParam = {};
                        sParam.cdNbr = "11308";
                        var linkData1 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                        // 채널코드
                        sParam = {};
                        sParam.cdNbr = "50002";
                        var linkData2 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                        // 상품대분류
                        sParam = {};
                        sParam.cdNbr = "80015";
                        var linkData3 = {"header": fn_getHeader("CAPCM0038400"), "CaCmnCdSvcGetCdListByCdNbrIn": sParam};


                        /* ========================================================== */
                        bxProxy.all([
                            /* ========================================================== */
                            // 제한유형콤보로딩
                            {
                                url: sUrl, param: JSON.stringify(linkData1), success: function (responseData) {
                                if (fn_commonChekResult(responseData)) {
                                    comboStore1 = new Ext.data.Store({
                                        fields: ['cd', 'cdNm'],
                                        data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tblNm
                                    });
                                }
                            }
                            }
                            // 채널코드콤보로딩
                            , {
                                url: sUrl, param: JSON.stringify(linkData2), success: function (responseData) {
                                    if (fn_commonChekResult(responseData)) {
                                        comboStore2 = new Ext.data.Store({
                                            fields: ['cd', 'cdNm'],
                                            data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tblNm
                                        });
                                    }
                                }
                            }
                            // 상품대분류콤보로딩
                            , {
                                url: sUrl, param: JSON.stringify(linkData3), success: function (responseData) {
                                    if (fn_commonChekResult(responseData)) {
                                        comboStore3 = new Ext.data.Store({
                                            fields: ['cd', 'cdNm'],
                                            data: responseData.CaCmnCdSvcGetCdListByCdNbrOut.tblNm
                                        });
                                    }
                                }
                            }
                 	          ], {
                            success: function () {


                            }
                        });


//                        /* ------------------------------------------------------------ */
                        that.CAPSV003Grid = new ExtGrid({
                            /* ------------------------------------------------------------ */
                            // 단일탭 그리드 컬럼 정의
                            fields: ['srvcRstrctnCd', 'seqNbr', 'rowIndex', 'srvcRstrctnStartDtm', 'srvcRstrctnEndDtm', 'srvcCd', 'srvcRstrctnTrgtCntnt', 'chnlCd', 'bizDscd', 'pdTpCd', 'pdTmpltCd', 'pdCd', 'lastChngTmstmp']
                            , id: 'CAPSV003Grid'
                            , columns: [
   							{
   								text: 'No.'
   							    , dataIndex: 'rowIndex'
   							    , sortable: false
   							    , width : 80
                                   , height: 25
   							    , style: 'text-align:center'
   							    , align: 'center'
   							    // other config you need....
   							    , renderer: function (value, metaData, record, rowIndex) {
   							        return rowIndex + 1;
   							    }
   							}
    							//서비스제한코드, 서비스제한시작일시, 서비스제한종료일시, 서비스코드, 서비스제한대상내용, 최종변경일시
                                , {
                                    text: bxMsg('cbb_items.AT#srvcRstrctnCd'),
                                    width: 100,
                                    dataIndex: 'srvcRstrctnCd',
                                    style: 'text-align:center',
                                    align: 'left'
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore1
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore1.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore1.getAt(index).data;
                                            return rs.cdNm;
                                        }
                                    } // end of render
                                } // end of srvcRstrctnCd
                                , {
                                    text: bxMsg('cbb_items.AT#srvcRstrctnStartDtm'),
                                    width: 200,
                                    dataIndex: 'srvcRstrctnStartDtm',
                                    style: 'text-align:center',
                                    align: 'center'
                                    ,
                                    renderer: function (val) {
                                        // return that.setGridData(val);
                                        return XDate(val).toString('yyyy-MM-dd HH:mm:ss');
                                    }
                                    ,
                                    editor: new Ext.form.DateField({
                                        allowBlank: false
                                        , xtype: 'datefield'
                                        , format: 'Y-m-d'
                                        , minValue: new Date()
                                    })
                                } // end of srvcRstrctnStartDtm
                                , {
                                    text: bxMsg('cbb_items.AT#srvcRstrctnEndDtm'),
                                    width: 200,
                                    dataIndex: 'srvcRstrctnEndDtm',
                                    style: 'text-align:center',
                                    align: 'center'
                                    ,
                                    renderer: function (val) {
                                        // return that.setGridData(val);
                                        return XDate(val).toString('yyyy-MM-dd HH:mm:ss');
                                    }
                                    ,
                                    editor: new Ext.form.DateField({
                                        allowBlank: false
                                        , xtype: 'datefield'
                                        , format: 'Y-m-d'
                                        , minValue: new Date()
                                    })
                                } // end of srvcRstrctnEndDtm
                                , {
                                    text: bxMsg('cbb_items.AT#srvcCd'),
                                    width: 150,
                                    dataIndex: 'srvcCd',
                                    style: 'text-align:center',
                                    align: 'left'
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#srvcRstrctnTrgtCntnt'),
                                    width: 600,
                                    dataIndex: 'srvcRstrctnTrgtCntnt',
                                    style: 'text-align:center',
                                    align: 'left',
                                    flex : 1
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#chnlCd'),
                                    width: 60,
                                    dataIndex: 'chnlCd',
                                    style: 'text-align:center',
                                    align: 'left',
                                    hidden: true
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore2
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore2.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore2.getAt(index).data;
                                            return rs.cdNm;
                                        }
                                    } // end of render
                                } // end of chnlCd
                                , {
                                    text: bxMsg('cbb_items.AT#bizDscd'),
                                    width: 80,
                                    dataIndex: 'bizDscd',
                                    style: 'text-align:center',
                                    align: 'left',
                                    hidden: true
                                    ,
                                    editor: {
                                        xtype: 'combobox'
                                        , store: comboStore3
                                        , displayField: 'cdNm'
                                        , valueField: 'cd'
                                    }
                                    ,
                                    renderer: function (val) {
                                        index = comboStore3.findExact('cd', val);
                                        if (index != -1) {
                                            rs = comboStore3.getAt(index).data;
                                            return rs.cdNm;
                                        }
                                    } // end of render
                                } // end of bizDscd
                                , {
                                    text: bxMsg('cbb_items.AT#pdTpCd'),
                                    width: 80,
                                    dataIndex: 'pdTpCd',
                                    style: 'text-align:center',
                                    align: 'left',
                                    hidden: true
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#pdTmpltCd'),
                                    width: 80,
                                    dataIndex: 'pdTmpltCd',
                                    style: 'text-align:center',
                                    align: 'left',
                                    hidden: true
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#pdCd'),
                                    width: 80,
                                    dataIndex: 'pdCd',
                                    style: 'text-align:center',
                                    align: 'left',
                                    hidden: true
                                }
                                , {
                                    text: bxMsg('cbb_items.AT#lastChngTmstmp'),
                                    width: 100,
                                    dataIndex: 'lastChngTmstmp',
                                    style: 'text-align:center',
                                    align: 'center',
                                    hidden: true
                                    ,
                                    renderer: function (val) {
                                        if (val != null)
                                        // return that.setGridData(val);
                                            return XDate(val).toString('yyyy-MM-dd');
                                    }
                                    ,
                                    editor: new Ext.form.DateField({
                                        allowBlank: false
                                        , xtype: 'datefield'
                                        , format: 'Y-m-d'
                                        , minValue: new Date()
                                    })
                                } // end of lastChngTmstmp
                                ] // end of columns
                            , listeners: {
                                click: {
                                    element: 'body'
                                    , fn: function () {
                                    	that.initFlag = false;
                                        //이벤트 발생시에 디테일 화면 렌더링
                                        that.selectRecord();
                                    }
                                }
                            }


                        });


                    }// end of initialize:


                    , clickBrowse: function () {
                        this.selectPSV003Base();
                    }
                    , selectRecord: function () {
                        var that = this;
                        if(!that.CAPSV003Grid.grid.getSelectionModel().selected.items[0]) return;
                        var selectedRecord = that.CAPSV003Grid.grid.getSelectionModel().selected.items[0].data;
                        var param = {};


                        if (!selectedRecord) {


                            return;
                        } else {


                        	 that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnCd"]').prop("disabled", true);


                             //   that.$el.find('#detail-information-area [data-form-param="balTpCd"]').prop("disabled", true);
                                that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnCd"]').val(selectedRecord.srvcRstrctnCd);
                                that.$el.find('#CAPSV003-detail-table [data-form-param="srvcCd"]').val(selectedRecord.srvcCd);
                                that.$el.find('#CAPSV003-detail-table [data-form-param="chnlCd"]').val(selectedRecord.chnlCd);


                                if(selectedRecord.bizDscd != undefined && selectedRecord.bizDscd != "" ){
                                	that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').val(selectedRecord.bizDscd);


                                }else{
                                	that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').val("");
                                }


                                if(selectedRecord.pdTpCd != undefined && selectedRecord.pdTpCd != "" ){
                                	param = {};
                                	param.bizDscd =selectedRecord.bizDscd;
                                	param.pdTpCd = selectedRecord.pdTpCd;
                                	param.pdTmpltCd = selectedRecord.pdTmpltCd;
                                	that.selectPdMClcd2(param);
                                	that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').val(
                                			 selectedRecord.pdTpCd );


                                }else{
                                	that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').val("");
                                }
                                //0220002
                                if(selectedRecord.pdTmpltCd != undefined && selectedRecord.pdTmpltCd != "" ){
                                	param = {};
                                	param.bizDscd =selectedRecord.bizDscd;
                                	param.pdTpCd = selectedRecord.pdTpCd;
                                	param.pdTmpltCd = selectedRecord.bizDscd + selectedRecord.pdTpCd + selectedRecord.pdTmpltCd;
                                	that.selectPdTmpltCd2(param);
                                	that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').val(
                                			selectedRecord.bizDscd + selectedRecord.pdTpCd + selectedRecord.pdTmpltCd );






                                }else{
                                	that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').val("");
                                }


                                //01 02 2000200 000000001 //01022000200000000001
                                if(selectedRecord.pdCd != undefined && selectedRecord.pdCd != "" ){
                                	param.bizDscd =selectedRecord.bizDscd;
                                	param.pdTpCd = selectedRecord.pdTpCd;
                                	param.pdTmpltCd = selectedRecord.bizDscd + selectedRecord.pdTpCd + selectedRecord.pdTmpltCd;
                                	param.pdCd = selectedRecord.pdCd;
                                	that.selectPdCd2(param);
                                	that.$el.find('#CAPSV003-detail-table [data-form-param="pdCd"]').val(
                                	 selectedRecord.pdCd);




                                }else{
                                	that.$el.find('#CAPSV003-detail-table [data-form-param="pdCd"]').val("");
                                }


                                that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartDtm"]').val(XDate(selectedRecord.srvcRstrctnStartDtm).toString('yyyy-MM-dd'));
                                that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').val(XDate(selectedRecord.srvcRstrctnStartDtm).toString('HH:mm:ss'));
                                that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').val(XDate(selectedRecord.srvcRstrctnEndDtm).toString('yyyy-MM-dd'));
                                that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').val(XDate(selectedRecord.srvcRstrctnEndDtm).toString('HH:mm:ss'));


                          }                        
                    } // end of selectRecord






                    /* ======================================================================== */
                    /*    Click select btn                                                      */
                    /* ======================================================================== */
                    , selectPSV003Base: function () {
                        var that = this;
                        var param = {};


                        // 조회 key값 set
                        param.srvcRstrctnCd = this.$el.find('[data-form-param="srvcRstrctnCd"]').val(); // 제한코드
                        param.srvcCd = this.$el.find('[data-form-param="srvcCd"]').val(); // 서비스코드
                        param.chnlCd = this.$el.find('[data-form-param="chnlCd"]').val(); // 채널코드
                        param.bizDscd = this.$el.find('[data-form-param="bizDscd"]').val(); // 상품대분류
                        param.pdTpCd = this.$el.find('[data-form-param="pdTpCd"]').val(); // 상품중분류
                        param.pdTmpltCd = this.$el.find('[data-form-param="pdTmpltCd"]').val(); // 상품템플릿
                        param.pdCd = this.$el.find('[data-form-param="pdCd"]').val(); // 상품코드


                        that.trigger('loadData', param);


                    } // end of select function
                    /* ======================================================================== */
                    /*  상품 대분류코드 변경 event 처리 */
                    /* ======================================================================== */
                    , changeBizDscd: function () {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        var param = {};
                        // 상품대분류코드
                        var bizDscd = that.$el.find('#CAPSV003-base-table [data-form-param="bizDscd"]').val();


                        //상품중분류코드 재조회
                        param.bizDscd = bizDscd;
                        that.selectPdMClcd(param);
                    }
                    , changeBizDscd2: function () {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        var param = {};
                        // 상품대분류코드
                        var bizDscd = that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').val();


                        //상품중분류코드 재조회
                        param.bizDscd = bizDscd;
                        that.selectPdMClcd2(param);
                    }


                    /* ======================================================================== */
                    /*  상품 중분류코드 변경 event 처리 */
                    /* ======================================================================== */
                    , changePdMClcd: function () {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        var param = {};
                        // 상품중분류코드
                        var pdTpCd = that.$el.find('#CAPSV003-base-table [data-form-param="pdTpCd"]').val();


                        // 상품대분류코드+ 상품중분류코드
                        param.bizDscd = that.$el.find('#CAPSV003-base-table [data-form-param="bizDscd"]').val();
                        param.pdTpCd = pdTpCd;


                        //상품템플릿코드 재조회
                        that.selectPdTmpltCd(param);
                    }
                    , changePdMClcd2: function () {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        var param = {};
                        // 상품중분류코드
                        var pdTpCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').val();


                        // 상품대분류코드+ 상품중분류코드
                        param.bizDscd = that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').val();
                        param.pdTpCd = pdTpCd;


                        //상품템플릿코드 재조회
                        that.selectPdTmpltCd2(param);
                    }
                    /* ======================================================================== */
                    /*  상품 템플릿코드 변경 event 처리 */
                    /* ======================================================================== */
                    , changePdTmpltCd: function () {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        var param = {};
                        // 상품템플릿코드
                        var pdTmpltCd = that.$el.find('#CAPSV003-base-table [data-form-param="pdTmpltCd"]').val();


                        // 상품대분류코드 + 상품중분류코드 + 상품템플릿코드
                        param.bizDscd = that.$el.find('#CAPSV003-base-table [data-form-param="bizDscd"]').val();
                        param.pdTpCd = that.$el.find('#CAPSV003-base-table [data-form-param="pdTpCd"]').val();
                        param.pdTmpltCd = pdTmpltCd;




                        //상품템플릿코드 재조회
                        that.selectPdCd(param);
                    }
                    , changePdTmpltCd2: function () {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        var param = {};
                        // 상품템플릿코드
                        var pdTmpltCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').val();


                        // 상품대분류코드 + 상품중분류코드 + 상품템플릿코드
                        param.bizDscd = that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').val();
                        param.pdTpCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').val();
                        param.pdTmpltCd = pdTmpltCd;




                        //상품템플릿코드 재조회
                        that.selectPdCd2(param);
                    }
                    /* ======================================================================== */
                    /*  상품 중분류코드 조회 */
                    /* ======================================================================== */
                    , selectPdMClcd: function (param) {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        sParam = {}; //데이터 초기화
                        selectStyle = {}; //스타일 초기화


                        if (param.bizDscd == "") {
                            //상품중분류코드 초기화
                            that.initPdMClcd();
                        }
                        else {
                            //combobox 정보 셋팅
//                        	selectStyle = {'width':'80%'}
                        	 sParam.className = "CAPSV003-base-pdTpCd-wrap";
                            sParam.targetId = "pdTpCd";
                            sParam.nullYn = "Y";
                            //inData 정보 셋팅
                            sParam.instCd = commonInfo.getInstInfo().instCd;
                            sParam.bizDscd = param.bizDscd;
                            sParam.pdTpCd = "";
                            sParam.pdTmpltCd = "";
                            sParam.pdCd = "";


                            if (param.pdTpCd) {
                                sParam.selectVal = param.pdTpCd;
                                //sParam.disabled = true;
                            }


                            //상품중분류코드 콤보데이터 load
                            fn_getPdCodeList(sParam, this, selectStyle);
                        }


                        //상품템플릿 초기화
                        //that.initPdTmpltCd();
                    }
                    , selectPdMClcd2: function (param) {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        sParam = {}; //데이터 초기화
                        selectStyle = {}; //스타일 초기화


                        if (param.bizDscd == "") {
                            //상품중분류코드 초기화
                            that.initPdMClcd();
                        }
                        else {
                            //combobox 정보 셋팅
//                        	selectStyle = {'width':'80%'}
                        	 sParam.className = "CAPSV003-detail-pdTpCd-wrap";
                            sParam.targetId = "pdTpCd";
                            sParam.nullYn = "Y";
                            //inData 정보 셋팅
                            sParam.instCd = commonInfo.getInstInfo().instCd;
                            sParam.bizDscd = param.bizDscd;
                            sParam.pdTpCd = "";
                            sParam.pdTmpltCd = "";
                            sParam.pdCd = "";


                            if (param.pdTpCd) {
                                sParam.selectVal = param.pdTpCd;
                                //sParam.disabled = true;
                            }


                            //상품중분류코드 콤보데이터 load
                            fn_getPdCodeList(sParam, this, selectStyle);
                        }


                        //상품템플릿 초기화
                        //that.initPdTmpltCd();
                    }
                    /* ======================================================================== */
                    /*    상품코드 조회                                */
                    /* ======================================================================== */
                    , selectPdCd: function (param) {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        sParam = {}; //데이터 초기화
                        selectStyle = {}; //스타일 초기화


                        if (param.pdTmpltCd == "") {
                            //상품템플릿 초기화
                            that.initPdCd();
                        }
                        else {
                            //combobox 정보 셋팅
//                        	selectStyle = {'width':'80%'}
                        	sParam.className = "CAPSV003-base-pdCd-wrap";
                            sParam.targetId = "pdCd";
                            sParam.nullYn = "Y";
                            //inData 정보 셋팅
                            sParam.instCd = commonInfo.getInstInfo().instCd;
                            sParam.bizDscd = param.bizDscd;
                            sParam.pdTpCd = param.pdTpCd;
                            sParam.pdTmpltCd = param.pdTmpltCd;
                            sParam.pdCd = "";


                            if (param.pdCd) {
                                sParam.selectVal = param.pdCd; //초기값 셋팅
                                //sParam.disabled = true; //비활성화 처리
                            }


                            // 상품탬플릿코드 콤보데이터 load
                            fn_getPdCodeList(sParam, this, selectStyle);
                        }
                    }
                    /* ======================================================================== */
                    /*    상품코드 조회                                */
                    /* ======================================================================== */
                    , selectPdCd2: function (param) {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        sParam = {}; //데이터 초기화
                        selectStyle = {}; //스타일 초기화


                        if (param.pdTmpltCd == "") {
                            //상품템플릿 초기화
                            that.initPdCd();
                        }
                        else {
                            //combobox 정보 셋팅
//                        	selectStyle = {'width':'80%'}
                        	sParam.className = "CAPSV003-detail-pdCd-wrap";
                            sParam.targetId = "pdCd";
                            sParam.nullYn = "Y";
                            //inData 정보 셋팅
                            sParam.instCd = commonInfo.getInstInfo().instCd;
                            sParam.bizDscd = param.bizDscd;
                            sParam.pdTpCd = param.pdTpCd;
                            sParam.pdTmpltCd = param.pdTmpltCd;
                            sParam.pdCd = "";


                            if (param.pdCd) {
                                sParam.selectVal = param.pdCd; //초기값 셋팅
                                //sParam.disabled = true; //비활성화 처리
                            }


                            // 상품탬플릿코드 콤보데이터 load
                            fn_getPdCodeList(sParam, this, selectStyle);
                        }
                    }
                    /* ======================================================================== */
                    /*    상품탬플릿코드 조회                                */
                    /* ======================================================================== */
                    , selectPdTmpltCd: function (param) {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        sParam = {}; //데이터 초기화
                        selectStyle = {}; //스타일 초기화


                        if (param.pdTpCd == "") {
                            //상품템플릿 초기화
                            that.initPdTmpltCd();
                        }
                        else {
                            //combobox 정보 셋팅
//                        	selectStyle = {'width':'80%'}
                        	sParam.className = "CAPSV003-base-pdTmpltCd-wrap";
                            sParam.targetId = "pdTmpltCd";
                            sParam.nullYn = "Y";
                            //inData 정보 셋팅
                            sParam.instCd = commonInfo.getInstInfo().instCd;
                            sParam.bizDscd = param.bizDscd;
                            sParam.pdTpCd = param.pdTpCd;
                            sParam.pdTmpltCd = "";
                            sParam.pdCd = "";


                            if (param.pdTmpltCd) {
                                sParam.selectVal = param.pdTmpltCd; //초기값 셋팅
                                //sParam.disabled = true; //비활성화 처리
                            }


                            // 상품탬플릿코드 콤보데이터 load
                            fn_getPdCodeList(sParam, this, selectStyle);
                        }
                    }
                    , selectPdTmpltCd2: function (param) {
                        var that = this;
                        var sParam = {};
                        var selectStyle = {};
                        sParam = {}; //데이터 초기화
                        selectStyle = {}; //스타일 초기화


                        if (param.pdTpCd == "") {
                            //상품템플릿 초기화
                            that.initPdTmpltCd();
                        }
                        else {
                            //combobox 정보 셋팅
//                        	selectStyle = {'width':'80%'}
                        	sParam.className = "CAPSV003-detail-pdTmpltCd-wrap";
                            sParam.targetId = "pdTmpltCd";
                            sParam.nullYn = "Y";
                            //inData 정보 셋팅
                            sParam.instCd = commonInfo.getInstInfo().instCd;
                            sParam.bizDscd = param.bizDscd;
                            sParam.pdTpCd = param.pdTpCd;
                            sParam.pdTmpltCd = "";
                            sParam.pdCd = "";


                            if (param.pdTmpltCd) {
                                sParam.selectVal = param.pdTmpltCd; //초기값 셋팅
                                //sParam.disabled = true; //비활성화 처리
                            }


                            // 상품탬플릿코드 콤보데이터 load
                            fn_getPdCodeList(sParam, this, selectStyle);
                        }
                    }


                    , initPdMClcd: function () {
                        var sParam = {};
                        var selectStyle = {};
                        // 상품템플릿코드 리셋
//                    	selectStyle = {'width':'80%'}


                        sParam.className = "CAPSV003-base-pdCd-wrap";
                        sParam.targetId = "pdTpCd";
                        //상품중분류코드
                        fn_getEmptyCombo(sParam, this, selectStyle);
                    }


                    /* ======================================================================== */
                    /* 입출력 항목 set */
                    /* ======================================================================== */
                    , setDetlData: function (param) {
                        var that = this;


                        that.initFlag = false;
                        var sParam = {};


                        that.resetPSV003Detl();


                        // 조회 key항목 disabled 처리
                        //제한시작일
                        that.$el.find('[data-form-param="srvcRstrctnStartDtm"]').val(XDate(param.srvcRstrctnStartDtm).toString('yyyy-MM-dd'));
                        that.$el.find('[data-form-param="srvcRstrctnStartDtm"]').prop("disabled", false);


                        that.$el.find('[data-form-param="srvcRstrctnEndDtm"]').val(XDate(param.srvcRstrctnStartDtm).toString('yyyy-MM-dd'));
                        that.$el.find('[data-form-param="srvcRstrctnEndDtm"]').prop("disabled", false);
                        //제한시작시간
//                        that.$el.find('[data-form-param="srvcRstrctnStartTime"]').val(XDate(param.srvcRstrctnStartDtm).toString('HH:mm:ss'));
//                        that.$el.find('[data-form-param="srvcRstrctnStartTime"]').prop("disabled", false);
//                        //제한종료일
//                        that.$el.find('[data-form-param="srvcRstrctnEndDtm"]').val(XDate(param.srvcRstrctnEndDtm).toString('yyyy-MM-dd'));
//                        that.$el.find('[data-form-param="srvcRstrctnEndDtm"]').prop("disabled", false);
//                        //제한종료일
//                        that.$el.find('[data-form-param="srvcRstrctnEndTime"]').val(XDate(param.srvcRstrctnEndDtm).toString('HH:mm:ss'));
//                        that.$el.find('[data-form-param="srvcRstrctnEndTime"]').prop("disabled", false);
//                        //제한유형
//                        that.$el.find('[data-form-param="srvcRstrctnCd"]').val(param.srvcRstrctnCd);
//                        that.$el.find('[data-form-param="srvcRstrctnCd"]').prop("disabled", false);
//                        //일련번호
//                        that.$el.find('[data-form-param="seqNbr"]').val(param.seqNbr);
//                        that.$el.find('[data-form-param="seqNbr"]').prop("disabled", true);
//                        //서비스코드
//                        that.$el.find('[data-form-param="srvcCd"]').val(param.srvcCd);
//                        that.$el.find('[data-form-param="srvcCd"]').prop("disabled", false);
//                        //채널코드
//                        that.$el.find('[data-form-param="chnlCd"]').val(param.chnlCd);
//                        that.$el.find('[data-form-param="chnlCd"]').prop("disabled", false);
                        //상품대분류


                        if (param.srvcRstrctnCd == '01') {
                            sParam.bizDscd = param.bizDscd;
                            sParam.pdTpCd = param.pdTpCd;
                            sParam.pdTmpltCd = param.pdTmpltCd;
                            sParam.pdCd = param.pdCd;


                            if (!fn_isEmpty(sParam.bizDscd)) {
                                that.$el.find('[data-form-param="bizDscd"]').val(sParam.bizDscd);
                            }


                            if (!fn_isEmpty(sParam.pdTpCd)) {
                                that.selectPdMClcd(sParam);
                            }


                            if (!fn_isEmpty(sParam.pdTmpltCd)) {
                                that.selectPdTmpltCd(sParam);
                            }


                            if (!fn_isEmpty(sParam.pdCd)) {
                            	that.$el.find('[data-form-param="bizDscd"]').val(sParam.bizDscd);
                            	that.selectPdMClcd(sParam);
                            	that.selectPdTmpltCd(sParam);


                                that.selectPdCd(sParam);
                            }
                        }
                    }


                    /* ======================================================================== */
                    /*   입출력 항목 초기화
                     /* ======================================================================== */
                    , resetPSV003Detl: function () {
                        var that = this;
                        that.initFlag = true;


//                        //제한시작일
//                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnStartDtm"]').val(getCurrentDate("yyyy-mm-dd"));
//                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnStartDtm"]').prop("disabled", false);
////                        //제한시작시간
//                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnStartTime"]').val("00:00:00");
//                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnStartTime"]').prop("disabled", false);
//                        //제한종료일
//                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnEndDtm"]').val(getCurrentDate("yyyy-mm-dd"));
//                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnEndDtm"]').prop("disabled", false);
//                        //제한종료시간
//                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnEndTime"]').val("23:59:59");
//                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnEndTime"]').prop("disabled", false);
                        //제한유형
                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnCd"]').val("");
                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcRstrctnCd"]').prop("disabled", false);
                        //일련번호
                        that.$el.find('#CAPSV003-base-table [data-form-param="seqNbr"]').val("");
                        that.$el.find('#CAPSV003-base-table [data-form-param="seqNbr"]').prop("disabled", true);
                        //서비스코드
                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcCd"]').val("");
                        that.$el.find('#CAPSV003-base-table [data-form-param="srvcCd"]').prop("disabled", false);
                        //채널코드
                        that.$el.find('#CAPSV003-base-table [data-form-param="chnlCd"]').val("");
                        that.$el.find('#CAPSV003-base-table [data-form-param="chnlCd"]').prop("disabled", false);
                        //상품대분류
                        that.$el.find('#CAPSV003-base-table [data-form-param="bizDscd"]').val("");
                        that.$el.find('#CAPSV003-base-table [data-form-param="bizDscd"]').prop("disabled", false);
                        //상품중분류코드
                        that.$el.find('#CAPSV003-base-table [data-form-param="pdTpCd"]').val("");
                        that.$el.find('#CAPSV003-base-table [data-form-param="pdTpCd"]').prop("disabled", false);
                        //상품템플릿코드
                        that.$el.find('#CAPSV003-base-table [data-form-param="pdTmpltCd"]').val("");
                        that.$el.find('#CAPSV003-base-table [data-form-param="pdTmpltCd"]').prop("disabled", false);
                        //상품코드
                        that.$el.find('#CAPSV003-base-table [data-form-param="pdCd"]').val("");
                        that.$el.find('#CAPSV003-base-table [data-form-param="pdCd"]').prop("disabled", false);


                        //제한시작시간
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').val("00:00:00");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').prop("disabled", false);
                        //제한종료일
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').val(getCurrentDate("yyyy-mm-dd"));
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').prop("disabled", false);
                        //제한종료시간
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').val("23:59:59");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').prop("disabled", false);
                    }
                    , resetPSV003Detl2: function () {
                        var that = this;
                        that.initFlag = true;


                        //제한시작일
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartDtm"]').val(getCurrentDate("yyyy-mm-dd"));
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartDtm"]').prop("disabled", false);
//                        //제한시작시간
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').val("00:00:00");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').prop("disabled", false);
                        //제한종료일
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').val(getCurrentDate("yyyy-mm-dd"));
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').prop("disabled", false);
                        //제한종료시간
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').val("23:59:59");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').prop("disabled", false);
                        //제한유형
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnCd"]').val("");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnCd"]').prop("disabled", false);
                        //일련번호
                        that.$el.find('#CAPSV003-detail-table [data-form-param="seqNbr"]').val("");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="seqNbr"]').prop("disabled", true);
                        //서비스코드
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcCd"]').val("");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="srvcCd"]').prop("disabled", false);
                        //채널코드
                        that.$el.find('#CAPSV003-detail-table [data-form-param="chnlCd"]').val("");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="chnlCd"]').prop("disabled", false);
                        //상품대분류
                        that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').val("");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').prop("disabled", false);
                        //상품중분류코드
                        that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').val("");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').prop("disabled", false);
                        //상품템플릿코드
                        that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').val("");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').prop("disabled", false);
                        //상품코드
                        that.$el.find('#CAPSV003-detail-table [data-form-param="pdCd"]').val("");
                        that.$el.find('#CAPSV003-detail-table [data-form-param="pdCd"]').prop("disabled", false);
                    }


                    /* ======================================================================== */
                    /*   저장기능 (등록/수정) 처리
                     /* ======================================================================== */
                    , savePSV003Detl: function () {
                        var that = this;
                        var sParam = {};
                        var header = new Object();
                        var headerParam = {};

                      //배포처리[과제식별자 체크]
//                        if (!fn_headerTaskIdCheck()){
//                            return;
//                        }
                        
                        // 입력항목 set
                        // 제한시작일                
                        sParam.srvcRstrctnStartDtm = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartDtm"]').val();
                        // 제한시작시간
                        srvcRstrctnStartTime = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').val();
                        // 제한종료일
                        sParam.srvcRstrctnEndDtm = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').val();
                        // 제한종료시간
                        srvcRstrctnEndTime = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').val();
                        // 제한유형
                        sParam.srvcRstrctnCd = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnCd"]').val();


                        if(this.CAPSV003Grid.grid.getSelectionModel().selected.items[0] && !that.initFlag){
                        	 var selectedRecord = that.CAPSV003Grid.grid.getSelectionModel().selected.items[0].data;
                             // 일련번호
                             sParam.seqNbr = selectedRecord.seqNbr;
                        }else{
                        	sParam.seqNbr = that.$el.find('#CAPSV003-detail-table [data-form-param="seqNbr"]').val();
                        }


                        // 서비스코드
                        sParam.srvcCd = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcCd"]').val();


                        // 채널코드
                        sParam.chnlCd = that.$el.find('#CAPSV003-detail-table [data-form-param="chnlCd"]').val();
                        // 상품대분류
                        sParam.bizDscd = that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').val();
                        // 상품중분류코드
                        sParam.pdTpCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').val();
                        // 상품템플릿코드
                        sParam.pdTmpltCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').val();
                        // 상품코드
                        sParam.pdCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdCd"]').val();


                        // UICME0004 필수 입력 항목입니다.
                        // UICME0028 잘못된 입력 값이 있습니다.
                        // 입력 검증
//                        if(fn_isNull(sParam.srvcRstrctnStartDtm)) {
//                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0004') + " [" + bxMsg("cbb_items.AT#srvcRstrctnStartDtm") + "]");
//                        	that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartDtm"]').focus();
//                        	return;
//                        }
//
//                        if(fn_isNull(srvcRstrctnStartTime)) {
//                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0004') + " [" + bxMsg("cbb_items.AT#srvcRstrctnStartDtm") + "]");
//                        	that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').focus();
//                        	return;
//                        }
//
//                        if(fn_isNull(sParam.srvcRstrctnEndDtm)) {
//                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0004') + " [" + bxMsg("cbb_items.AT#srvcRstrctnEndDtm") + "]");
//                        	that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').focus();
//                        	return;
//                        }
//
//                        if(fn_isNull(srvcRstrctnEndTime)) {
//                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0004') + " [" + bxMsg("cbb_items.AT#srvcRstrctnEndDtm") + "]");
//                        	that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').focus();
//                        	return;
//                        }
//                        
////                        if(sParam.srvcRstrctnStartDtm < getCurrentDate("yyyy-mm-dd")) {
////                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#srvcRstrctnStartDtm") + "]");
////                        	that.$el.find('[data-form-param="srvcRstrctnStartDtm"]').focus();
////                        	return;
////                        }
//                        
//                        if(sParam.srvcRstrctnEndDtm < getCurrentDate("yyyy-mm-dd")) {
//                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#srvcRstrctnEndDtm") + "]");
//                        	that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').focus();
//                        	return;
//                        }
//
//                        if(fn_isNull(sParam.srvcRstrctnCd)) {
//                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0004') + " [" + bxMsg("cbb_items.AT#srvcRstrctnCd") + "]");
//                        	that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnCd"]').focus();
//                        	return;
//                        }
//                        
//                        if(fn_isNull(sParam.srvcCd)) {
//                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0004') + " [" + bxMsg("cbb_items.AT#srvcCd") + "]");
//                        	that.$el.find('#CAPSV003-detail-table [data-form-param="srvcCd"]').focus();
//                        	return;
//                        }
//                        
//                        // 상품
//                        if(sParam.srvcRstrctnCd == "01") {
//                        	if(fn_isNull(sParam.bizDscd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0004') + " [" + bxMsg("cbb_items.AT#bizDscd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').focus();
//                            	return;
//                            }
//                        	
//                        	if(!fn_isNull(sParam.chnlCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#chnlCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="chnlCd"]').focus();
//                            	return;
//                            }
//                        }
//                        
//                        // 채널
//                        if(sParam.srvcRstrctnCd == "02") {
//                        	if(fn_isNull(sParam.chnlCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0004') + " [" + bxMsg("cbb_items.AT#chnlCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="chnlCd"]').focus();
//                            	return;
//                            }
//                        	
//                        	if(!fn_isNull(sParam.bizDscd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#bizDscd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').focus();
//                            	return;
//                            }
//                        	
//                        	if(!fn_isNull(sParam.pdTpCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#pdTpCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').focus();
//                            	return;
//                            }
//                        	
//                        	if(!fn_isNull(sParam.pdTmpltCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#pdTmpltCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').focus();
//                            	return;
//                            }
//                        	
//                        	if(!fn_isNull(sParam.pdCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#pdCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="pdCd"]').focus();
//                            	return;
//                            }
//                        }
//
//                        // 서비스
//        				if(sParam.srvcRstrctnCd == "03") {
//                        	if(!fn_isNull(sParam.chnlCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#chnlCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="chnlCd"]').focus();
//                            	return;
//                            }
//        					
//                        	if(!fn_isNull(sParam.bizDscd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#bizDscd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').focus();
//                            	return;
//                            }
//                        	
//                        	if(!fn_isNull(sParam.pdTpCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#pdTpCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').focus();
//                            	return;
//                            }
//                        	
//                        	if(!fn_isNull(sParam.pdTmpltCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#pdTmpltCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').focus();
//                            	return;
//                            }
//                        	
//                        	if(!fn_isNull(sParam.pdCd)) {
//                            	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#pdCd") + "]");
//                            	that.$el.find('#CAPSV003-detail-table [data-form-param="pdCd"]').focus();
//                            	return;
//                            }
//        				}


                        // 시간일시 데이터 가공(ex. 2015-06-30 --> 2015-06-30T00:00:00+0900)
                        sParam.srvcRstrctnStartDtm = that.formatDate(sParam.srvcRstrctnStartDtm, srvcRstrctnStartTime);
                        sParam.srvcRstrctnEndDtm = that.formatDate(sParam.srvcRstrctnEndDtm, srvcRstrctnEndTime);
                        sParam.instCd =  $.sessionStorage('headerInstCd');


//                        if(sParam.srvcRstrctnStartDtm > sParam.srvcRstrctnEndDtm) {
//                        	alertMessage.error(bxMsg('cbb_err_msg.AUICME0028') + " [" + bxMsg("cbb_items.AT#srvcRstrctnStartDtm") + "]");
//                        	that.$el.find('[data-form-param="srvcRstrctnStartDtm"]').focus();
//                        	return;
//                        }


                        if (sParam.seqNbr == null) {  // 등록
                            var linkData = {"header": fn_getHeader("CAPSV0038101"), "CaSrvcRstrctnDtlMgmtSvcSrvcRstrctnDtlIn": sParam};
                        }
                        else {
                            var linkData = {"header": fn_getHeader("CAPSV0038201"), "CaSrvcRstrctnDtlMgmtSvcSrvcRstrctnDtlIn": sParam};
                        }




                        // ajax 호출
                        bxProxy.post(sUrl, JSON.stringify(linkData), {
                            enableLoading: true,
                            success: function (responseData) {
                                if (fn_commonChekResult(responseData)) {
                                  //  alertMessage.info("",bxMsg('cbb_items.SCRNITM#success'));
                                	//that.resetPSV003Detl2();
                                    // 재조회
                                	that.select();
                                }
                            } // end of success: function
                        }); // end of bxProxy
                    } // end of savePSV003Detl: function


                    /* ======================================================================== */
                    /*   날짜 + 시간 포맷팅 처리
                     /* ======================================================================== */
                    , formatDate: function (dateParam, timeParam) {
                        var dParam = dateParam;
                        var tParam = timeParam;
                        var afterFormatParam = "";


                        afterFormatParam = dateParam.concat('T').concat(tParam).concat('+0900');
                        // afterFormatParam = afterFormatParam.replace(/-/gi, '');


                        return afterFormatParam;
                    }
                    , loadDatePicker: function () {
                  	  fn_makeDatePicker(this.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartDtm"]'));
                  	  fn_makeDatePicker(this.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]'));


                  }


                   ,deletePSV003Detl: function (event) {
                        var that = this;
                        
                      //배포처리[과제식별자 체크]
//                        if (!fn_headerTaskIdCheck()){
//                            return;
//                        }

                        function deleteData() {
                            var sParam = {};
                            var sParam2 = {};
                            sParam2.tblNm = [];


                            // fn_confirmMessage(event,bxMsg('cbb_items.SCRNITM#data-delete-msg'), function () {
                            // 제한시작일
                            sParam.srvcRstrctnStartDtm = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartDtm"]').val();
                            // 제한시작시간
                            srvcRstrctnStartTime = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnStartTime"]').val();
                            // 제한종료일
                            sParam.srvcRstrctnEndDtm = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndDtm"]').val();
                            // 제한종료시간
                            srvcRstrctnEndTime = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnEndTime"]').val();
                            // 제한유형
                            sParam.srvcRstrctnCd = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcRstrctnCd"]').val();
                            if(!that.CAPSV003Grid.grid.getSelectionModel().selected.items[0]) return;
                            var selectedRecord = that.CAPSV003Grid.grid.getSelectionModel().selected.items[0].data;
                            // 일련번호
                            sParam.seqNbr = selectedRecord.seqNbr;
                            // 서비스코드
                            sParam.srvcCd = that.$el.find('#CAPSV003-detail-table [data-form-param="srvcCd"]').val();
                            // 채널코드
                            sParam.chnlCd = that.$el.find('#CAPSV003-detail-table [data-form-param="chnlCd"]').val();
                            // 상품대분류
                            sParam.bizDscd = that.$el.find('#CAPSV003-detail-table [data-form-param="bizDscd"]').val();
                            // 상품중분류코드
                            sParam.pdTpCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdTpCd"]').val();
                            // 상품템플릿코드
                            sParam.pdTmpltCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdTmpltCd"]').val();
                            // 상품코드
                            sParam.pdCd = that.$el.find('#CAPSV003-detail-table [data-form-param="pdCd"]').val();


                            // 시간일시 데이터 가공
                            sParam.srvcRstrctnStartDtm = that.formatDate(sParam.srvcRstrctnStartDtm, srvcRstrctnStartTime);
                            sParam.srvcRstrctnEndDtm = that.formatDate(sParam.srvcRstrctnEndDtm, srvcRstrctnEndTime);
                            sParam.instCd = $.sessionStorage('headerInstCd'); // 헤더의 기관코드


                            sParam2.tblNm.push(sParam);
                            var linkData = {"header": fn_getHeader("CAPSV0038301"), "CaSrvcRstrctnDtlMgmtSvcSrvcRstrctnDtlIn": sParam2};




                            // ajax호출
                            bxProxy.post(sUrl, JSON.stringify(linkData), {
                                enableLoading: true
                                , success: function (responseData) {
                                    if (fn_commonChekResult(responseData)) {
                                        fn_alertMessage("", bxMsg('cbb_items.SCRNITM#success'));
                                        that.select();


                                        // tree 재조회
//                                        that.loadTreeList();
//                                        
//                                        // 전체 초기화
//                                        that.resetBaseAttribute();
//                                        that.resetServiceInputItem();
//                                        that.resetServiceProfile();
//                                        that.resetTransactionRestriction();
                                    }
                                }   // end of suucess: fucntion
                            }); // end of bxProxy
                        }


                        fn_confirmMessage(event, bxMsg('cbb_items.SCRNITM#B_delete'), bxMsg('cbb_items.SCRNITM#data-delete-msg'), deleteData, this);
                    }


    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////  render                    /////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                    , render: function () {
                    	var that = this;
                        this.setTimeInput();
                        // 데이트 피커 로드
                        this.loadDatePicker();
//                    	// 콤보데이터 로딩
                        var sParam;
                        var selectStyle = {};
//                        that.$el.find('.CAPSV003-base-table #trnsfrKndNm').html("ABRVTN_NAME");
                       // this.$el.find("#CAPSV003-grid").html(this.CAPSV003Grid.render({'height': CaGridHeight}));
                        this.$el.find("#CAPSV003-grid").html(this.CAPSV003Grid.render({
                            'height': CaGridHeight
                        }));
//
                        sParam = {};


                        //제한코드
//                           selectStyle = {'width':'80%'};
                        sParam.className = "CAPSV003-base-srvcRstrctnCd-wrap";
                        sParam.targetId = "srvcRstrctnCd";
                        sParam.nullYn = "Y";
                        sParam.cdNbr = "11308";
                        fn_getCodeList(sParam, this, selectStyle);


                        //채널코드
                        sParam = {};
//                           selectStyle = {'width':'80%'};
                        sParam.className = "CAPSV003-base-chnlCd-wrap";
                        sParam.targetId = "chnlCd";
                        sParam.nullYn = "Y";
                        sParam.cdNbr = "50002";
                        fn_getCodeList(sParam, this, selectStyle);


                        //상품대분류
                        sParam = {};
//                           selectStyle = {'width':'80%'};
                        sParam.className = "CAPSV003-base-bizDscd-wrap";
                        sParam.targetId = "bizDscd";
                        sParam.nullYn = "Y";
                        sParam.cdNbr = "80015";
                        fn_getCodeList(sParam, this, selectStyle);


                      /////////////////////////////////////////////////////  
                        sParam = {};


                        //제한코드
//                           selectStyle = {'width':'80%'};
                        sParam.className = "CAPSV003-detail-srvcRstrctnCd-wrap";


                        sParam.targetId = "srvcRstrctnCd";
                        sParam.nullYn = "Y";
                        sParam.cdNbr = "11308";
                        fn_getCodeList(sParam, this, selectStyle);


                        //채널코드
                        sParam = {};
//                           selectStyle = {'width':'80%'};
                        sParam.className = "CAPSV003-detail-chnlCd-wrap";
                        sParam.targetId = "chnlCd";
                        sParam.nullYn = "Y";
                        sParam.cdNbr = "50002";
                        fn_getCodeList(sParam, this, selectStyle);


                        //상품대분류
                        sParam = {};
//                           selectStyle = {'width':'80%'};
                        sParam.className = "CAPSV003-detail-bizDscd-wrap";
                        sParam.targetId = "bizDscd";
                        sParam.nullYn = "Y";
                        sParam.cdNbr = "80015";
                        fn_getCodeList(sParam, this, selectStyle);


                        //상품중분류코드 초기화
                       // that.initPdMClcd();


                        //상품템플릿 초기화
                      //  that.initPdTmpltCd();


                        //상품코드 초기화
                      //  that.initPdCd();


                        // 날짜타입 컬럼 초기화
//                        var srvcRstrctnStartDtm = this.subViews['srvcRstrctnStartDtm'].getValue();
//                        if (srvcRstrctnStartDtm == null || srvcRstrctnStartDtm == "") {
//                            this.subViews['srvcRstrctnStartDtm'].setValue(getCurrentDate("yyyy-mm-dd"));
//                        }
//
//                        var srvcRstrctnEndDtm = this.subViews['srvcRstrctnEndDtm'].getValue();
//                        if (srvcRstrctnEndDtm == null || srvcRstrctnEndDtm == "") {
//                            this.subViews['srvcRstrctnEndDtm'].setValue(getCurrentDate("yyyy-mm-dd"));
//                        }
                        // 기본부 초기화 
                        this.resetPSV003Detl();


                      //배포처리반영[버튼비활성화]
//                        fn_btnCheckForDistribution([
//                                            		this.$el.find('.CAPSV003-wrap #btn-detail-save')
//                                            		,this.$el.find('.CAPSV003-wrap #btn-detail-delete')
//                                            			   ]);
                    	return that.$el;
                    }






            }); // end of Backbone.View.extend({


            return CAPSV003View;
        } // end of define function
    )
    ; // end of define
