// Generated by  on 2015-01-27 오후 5:15:30
define(
  [
      'app/views/page/PWF/504/PWF504-base',
      'app/views/page/PWF/504/PWF504-list',
//      'app/views/page/PWF/504/PWF504-detl',
      'text!app/views/page/PWF/504/_PWF504-tpl.html'
  ],
  function (
      PWF504Base,
      PWF504List,
//      PWF504Detl,
      tpl
  ) {


      var PWF504View = Backbone.View.extend({


          // 태그이름 설정
          tagName: 'section'


          // 클래스이름 설정
          ,className: 'bx-container bxp-PWF504001-page'


          // 템플릿 설정
          ,templates: {
              'tpl': tpl
          }


          ,initialize: function (initData) {
              var that = this;


              $.extend(that, initData);
              // 페이지 템플릿 설정
              that.$el.html(that.tpl());


              // 페이지 핸들바 설정 : 메뉴의 메인 페이지에 설정해야 함 (_PWF504.js파일)
              that.$el.attr('data-page', that.pageHandler);


              // 기본정보영역 객체 생성
              that.subViews['PWF504Base'] = new PWF504Base();


              // 탭(그리드)영역 객체 생성
              that.subViews['PWF504List'] = new PWF504List();
/*
              // 그리드 행별영역 객체 생성
              that.subViews['PWF504Detl'] = new PWF504Detl();*/


              // 초기화
              that.listenTo(that.subViews['PWF504Base'], 'reset', function() {
                  that.subViews['PWF504List'].reset();
//                  that.subViews['PWF504Detl'].reset();
              });


              // tab의 현재 활성화된 그리드 조회
              that.listenTo(that.subViews['PWF504Base'], 'loadData', function(param) {
                  that.subViews['PWF504List'].renderSubPage(param);
              });


//              that.listenTo(that.subViews['PWF504List'], 'loadProcessInstanceData', function(param){
//            	  that.subViews['PWF504Detl'].renderProcessInstanceDetail(param);
//              });
          } // end of initialize


          ,render: function() {
              // 기본정보영역 render
              this.$el.find('.PWF504-base-wrap').html(this.subViews['PWF504Base'].render());


              // 탭(그리드)정보영역 render
              this.$el.find('.PWF504-list-wrap').html(this.subViews['PWF504List'].render());
/*
              // 그리드 행별정보영역 render
              this.$el.find('.PWF504-detl-wrap').html(this.subViews['PWF504Detl'].render());*/


              return this.$el;
          } // end of render
      });// Backbone.View.extend


      return PWF504View;


  } // end of function
);
