// Generated by Bankware Global CBB Solution Center on 2015-02-03 오후 3:26:10


define(
  [
      'app/views/page/PWF/508/PWF508-base',
      'app/views/page/PWF/508/PWF508-list',
      'app/views/page/PWF/508/PWF508-detl',
      'text!app/views/page/PWF/508/_PWF508-tpl.html'
  ],
  function (
      PWF508Base,
      PWF508List,
      PWF508Detl,
      tpl
  ) {
	  var param = {};


      var PWF508View = Backbone.View.extend({


          // 태그이름 설정
          tagName: 'section'


          // 클래스이름 설정
          ,className: 'bx-container bxp-PWF508-page'


          // 템플릿 설정
          ,templates: {
              'tpl': tpl
          }


          ,initialize: function (initData) {
              var that = this;


              $.extend(that, initData);


              // 페이지 템플릿 설정
              that.$el.html(that.tpl());


              // 페이지 핸들바 설정 : 메뉴의 메인 페이지에 설정해야 함 (_.js파일)
              that.$el.attr('data-page', that.pageHandler);


              //목록페이지에서 넘어온 데이터
              param = initData.param;
              //alert("initParam"+initParam)


              // 기본정보영역 객체 생성
              that.subViews['PWF508Base'] = new PWF508Base(this.param);


              // 그리드정보영역 객체 생성
              that.subViews['PWF508List'] = new PWF508List();


              // 상세정보영역 객체 생성
              that.subViews['PWF508Detl'] = new PWF508Detl();


              // 그리드 조회
              that.listenTo(that.subViews['PWF508Base'], 'loadData', function(param) {
                  that.subViews['PWF508List'].renderSubPage(param);
              });


              //  List초기화
              that.listenTo(that.subViews['PWF508Base'], 'initList', function(param) {
                  that.subViews['PWF508List'].initList(param);
              });


              // Dtl초기화
              that.listenTo(that.subViews['PWF508List'], 'initDetl', function(param) {
                  that.subViews['PWF508Detl'].resetPWF508Detl(param);
              });


              // List의 현재 선택된 값을 상세로 bind
              that.listenTo(that.subViews['PWF508List'], 'loadDtlData', function(param) {
                  that.subViews['PWF508Detl'].selDtlData(param);
              });


              // detl로 aprvlCndNbr
              that.listenTo(that.subViews['PWF508Base'], 'loadAprvlCndNbr', function(param) {
                  that.subViews['PWF508Detl'].loadAprvlCndNbr(param);
              });


              // detl의 등록,수정,삭제후 상세로 bind
              that.listenTo(that.subViews['PWF508Detl'], 'loadData', function(param) {
                  that.subViews['PWF508List'].renderSubPage(param);
              });


          } // end of initialize


          ,render: function() {
              // 기본정보영역 render
              this.$el.find('.PWF508-base-wrap').html(this.subViews['PWF508Base'].render());


              // 그리드정보영역 render
              this.$el.find('.PWF508-list-wrap').html(this.subViews['PWF508List'].render());


              // 상세정보영역 render
              this.$el.find('.PWF508-detl-wrap').html(this.subViews['PWF508Detl'].render());


              return this.$el;
          } // end of render
      });// Backbone.View.extend


      return PWF508View;


  } // end of function
);
