// Generated by Bankware Global CBB Solution Center on 2015-02-04 오전 12:27:22


define(
  [
      'app/views/page/PWF/011/PWF011-base',
      'app/views/page/PWF/011/PWF011-list',
      'text!app/views/page/PWF/011/_PWF011-tpl.html'
  ],
  function (
      PWF011Base,
      PWF011List,
      tpl
  ) {


      var PWF011View = Backbone.View.extend({


          // 태그이름 설정
          tagName: 'section'


          // 클래스이름 설정
          ,className: 'bx-container bxp-PWF011-page'


          // 템플릿 설정
          ,templates: {
              'tpl': tpl
          }


          ,initialize: function (initData) {
              var that = this;


              $.extend(that, initData);


              // 페이지 템플릿 설정
              that.$el.html(that.tpl());


              // 페이지 핸들바 설정 : 메뉴의 메인 페이지에 설정해야 함 (_.js파일)
              that.$el.attr('data-page', that.pageHandler);


              // 기본정보영역 객체 생성
              that.subViews['PWF011Base'] = new PWF011Base();


              // 그리드정보영역 객체 생성
              that.subViews['PWF011List'] = new PWF011List();


              // tab의 현재 활성화된 그리드 조회
              that.listenTo(that.subViews['PWF011Base'], 'loadData', function(param) {
                  that.subViews['PWF011List'].renderSubPage(param);
              });


          } // end of initialize


          ,render: function() {
              // 기본정보영역 render
              this.$el.find('.PWF011-base-wrap').html(this.subViews['PWF011Base'].render());


              // 그리드정보영역 render
              this.$el.find('.PWF011-list-wrap').html(this.subViews['PWF011List'].render());


              return this.$el;
          } // end of render
      });// Backbone.View.extend


      return PWF011View;


  } // end of function
);
