// Generated by Bankware Global CBB Solution Center on 2015-02-04 오전 12:27:22


define(
    [
         'bx/common/config'
         ,'bx-component/message/message-alert'
         ,'bx-component/message/message-confirm'
         ,'bx-component/date-picker/_date-picker'
         ,'text!app/views/page/PWF/011/PWF011-base-tpl.html'
         ,'app/views/page/popup/CAPCM/popup-message'
         ,'app/views/page/popup/popup-wflowId'
         ,'bx/common/common-info'
   ],
   function (
         config
         , alertMessage
         , confirmMessage
         , DatePicker
         , tpl
         , PopupMessage
         , PopupWflowId
         ,commonInfo
   ){


         var PWF011BaseView = Backbone.View.extend({
               // 태그이름 설정
               tagName: 'section',
               // 클래스이름 설정
               className: 'PWF011-base-page',
               // 탬플릿 설정
               templates: {
                   'tpl': tpl
               }
               // 이벤트 설정
               , events: {
                    'click .PWF011-reset-btn': 'resetPWF011Base'
                   ,'click #STPop1': 'fn_popupMessage'
                   ,'click .PWF011-select-btn': 'selectPWF011Base'	   
            	   ,'click #wflowIdPop': 'popUpBrowseWflowId'
               }


               , initialize: function (initData) {
                   var that = this;
                   var initFlag = true;


                   // initData 저장
                   $.extend(that, initData);


                   // 페이지 템플릿 설정
                   that.$el.html(that.tpl());
               }


               , render: function() {
                   var that = this;
                   // 데이터 피커 로드
                   this.loadDatePicker();


                   // 콤보데이터 로딩
                   var sParam = {};
                   var selectStyle = {};




                   // wflowTpCd
                   sParam = {};
                   selectStyle = {"width":"100%"};
                   sParam.className = "PWF011-wflowTpCd-wrap";
                   sParam.targetId = "prcsTp";
                   sParam.nullYn = "Y";
                   sParam.cdNbr = "11905";
                   fn_getCodeList(sParam, this, selectStyle);


                   // aplyStsDstnctn
                   sParam = {};
                   selectStyle = {"width":"100%"};
                   sParam.className = "PWF011-aplyStsDstnctn-wrap";
                   sParam.targetId = "aplyStsDstnctn";
                   sParam.nullYn = "Y";
                   sParam.cdNbr = "11902";
                   fn_getCodeList(sParam, this, selectStyle);


                   // bizCmpntCd
                   sParam = {};
                   selectStyle = {"width":'100%'};
                   sParam.className = "PWF011-bizCmpntCd-wrap";
                   sParam.targetId = "bizCmpntCd";
                   sParam.nullYn = "Y";
                   sParam.cdNbr = "11603";
                   fn_getCodeList(sParam, this, selectStyle);


                   // 날짜타입 컬럼 초기화


                   // 기본부 초기화 
                   this.setPWF011BaseData(this, "", "X");


                   return this.$el;
               }


               /* ======================================================================== */
               // 입출력항목 setting
               /* ======================================================================== */
               , setPWF011BaseData: function(that, responseData, type) {
                   that = this;


                   if(type == "X") {  // 초기화
                       that.$el.find('[data-form-param="prcsId"] option:eq(0)').attr("selected", "selected");
                       that.$el.find('[data-form-param="prcsNm"]').val("");
                       that.$el.find('[data-form-param="prcsTp"] option:eq(0)').attr("selected", "selected");
                       that.$el.find('[data-form-param="aplyStsDstnctn"] option:eq(0)').attr("selected", "selected");
                       that.$el.find('[data-form-param="bizCmpntCd"] option:eq(0)').attr("selected", "selected");
                   }
                   else {
                       that.$el.find('[data-form-param="prcsId"]').val(responseData.prcsId);
                       that.$el.find('[data-form-param="prcsNm"]').val(responseData.prcsNm);
                       that.$el.find('[data-form-param="prcsTp"]').val(responseData.prcsTp);
                       that.$el.find('[data-form-param="aplyStsDstnctn"]').val(responseData.aplyStsDstnctn);
                       that.$el.find('[data-form-param="bizCmpntCd"]').val(responseData.bizCmpntCd);
                   }
              }


               /* ======================================================================== */
               /*    Click reset btn                                                       */
               /* ======================================================================== */
               , resetPWF011Base: function (e) {
                   var initFlag = false;
                   this.setPWF011BaseData(this, "", "X");
                   this.$el.find('[data-form-param="prcsId"]').focus();
               }


               /* ======================================================================== */
               /*    목록조회  팝업     테스트                                */
               /* ======================================================================== */
                , fn_popupMessage: function() {
                	var that = this;
                	var param = {};	


                	param.type = "03";
                	param.data =that.$el.find('[data-form-param="custNm"]').val(); //고객식별자명


                	var popupAcctgItm = new PopupAcctgItm(param); // 팝업생성
                	popupAcctgItm.render();


                	popupAcctgItm.on('popUpSetData', function(param) {
            		 that.$el.find('[data-form-param="bizCmpntCd"]').val(param.custId);
//            		 that.$el.find('[data-form-param="custNm"]').val(param.custNm);
            	 });
                }
               /* ======================================================================== */
               /*    Click select btn                                                      */
               /* ======================================================================== */
               , selectPWF011Base: function () {
                   var that = this;
                   var param = {};


                   var instCd = fn_getInstCd(commonInfo.getInstInfo().instCd);


               		if (instCd == null) {
                       alertMessage.info(bxMsg('cbb_items.SCRNITM#instSearchMsg'));
                       return;
                   }


                   // 조회 key값 set
                   param.instCd = instCd;
                   param.wflowId = this.$el.find('[data-form-param="wflowId"]').val();


                   that.trigger('loadData', param);


               } // end of select function


            , loadDatePicker: function() {


            }


            /* ======================================================================== */
            /*   워크플로우식별자 조회 팝업                                     */
            /* ======================================================================== */
            , popUpBrowseWflowId : function() {
                var that = this;
                var param = {};


                var instInfo = commonInfo.getInstInfo();
                param.instCd = instInfo.instCd;


                var popupWflowId = new PopupWflowId(param); // 팝업생성
                popupWflowId.render();


                popupWflowId.on('popUpSetData', function(param) {
                    that.$el.find('[data-form-param="wflowId"]').val(param.wflowId); // 워크플로우식별자
                    that.$el.find('[data-form-param="wflowNm"]').val(param.wflowNm); // 워크플로우명
                });
            }
        }); // end of Backbone.View.extend({


       return PWF011BaseView;


     } // end of define function
); // end of define
